## Production Systems Analysis Project
Owners: Almog Asraf, Daniel Pidtylok, Nir Levanon, Shani Yorav

### Imports

In [1]:
import numpy as np
import pandas as pd

### Parameters

In [2]:
J = 50 # Numbers of the orders

Creating the amount of vegtables, fruits and others from poission destribution:

In [3]:
lamb = [7.5, 5.2, 20] # Lambdas for the poission destribution
m = {1:[],2:[],3:[]} # 1: veggies, 2: fruits, 3: other
for i in m.keys(): # For each type of order
    for j in range(J): # For each order
        m[i].append(np.random.poisson(lamb[i-1]))
m_df = pd.DataFrame(m) # More easy to work with pandas df
m_df

     1   2   3
0    9   8  19
1    7  15  23
2    9   3  21
3    7   2  16
4    7   6  23
5    7   4  18
6    8   6  13
7    7   7  21
8    8   4  22
9    9   5  13
10   7   5  21
11  11   5  21
12   8   6  23
13   7   4  23
14   6   5  15
15   6   4  13
16  10   6  28
17  10   3  28
18   9   8  24
19  12   2  14
20   5   7  18
21   7   0  23
22   9   7  18
23   4   7  18
24   7   4  18
25   6   3  24
26  12   3  21
27   9   5  13
28   7   8  20
29  10   8  33
30  12   5  15
31   5   3  21
32   8   9  23
33   6   6  22
34   7   9  17
35   4   4  15
36   7   7  20
37  12   7  22
38  11   4  22
39  12   8  23
40   8   1  19
41   6   9  21
42   5   3  14
43   9   7  18
44   5   2  15
45   8  11  19
46  10   6  18
47  11   3  20
48   3   6  12
49   3   4  27

Creating the velocity matrix for each order:

In [4]:
v = {"veg":[],"fru":[], "oth":[]} # A dataframe of collector's velocity
for i in v.keys(): # For each type of order
    for j in range(J): # For each order
        if i == "veg":
            v[i].append((25/(25+25*m[1][j]))**1.2)
        elif i == "fru":
            v[i].append((25/(25+30*m[2][j]))**1.1)
        else:
            v[i].append(25/(25+10*m[3][j]))
v_df = pd.DataFrame(v) # More easy to work with pandas
v_df

         veg       fru       oth
0   0.063096  0.074501  0.116279
1   0.082469  0.039208  0.098039
2   0.063096  0.186624  0.106383
3   0.082469  0.260239  0.135135
4   0.082469  0.098811  0.098039
5   0.082469  0.144620  0.121951
6   0.071599  0.098811  0.161290
7   0.082469  0.085027  0.106383
8   0.071599  0.144620  0.102041
9   0.063096  0.117596  0.161290
10  0.082469  0.117596  0.106383
11  0.050697  0.117596  0.106383
12  0.071599  0.098811  0.098039
13  0.082469  0.144620  0.098039
14  0.096802  0.117596  0.142857
15  0.096802  0.144620  0.161290
16  0.056277  0.098811  0.081967
17  0.056277  0.186624  0.081967
18  0.063096  0.074501  0.094340
19  0.046054  0.260239  0.151515
20  0.116471  0.085027  0.121951
21  0.082469  1.000000  0.098039
22  0.063096  0.085027  0.121951
23  0.144956  0.085027  0.121951
24  0.082469  0.144620  0.121951
25  0.096802  0.186624  0.094340
26  0.046054  0.186624  0.106383
27  0.063096  0.117596  0.161290
28  0.082469  0.074501  0.111111
29  0.056277  0.074501  0.070423
30  0.046054  0.117596  0.142857
31  0.116471  0.186624  0.106383
32  0.071599  0.066211  0.098039
33  0.096802  0.098811  0.102041
34  0.082469  0.066211  0.128205
35  0.144956  0.144620  0.142857
36  0.082469  0.085027  0.111111
37  0.046054  0.085027  0.102041
38  0.050697  0.144620  0.102041
39  0.046054  0.074501  0.098039
40  0.071599  0.420083  0.116279
41  0.096802  0.066211  0.106383
42  0.116471  0.186624  0.151515
43  0.063096  0.085027  0.121951
44  0.116471  0.260239  0.142857
45  0.071599  0.054011  0.116279
46  0.056277  0.098811  0.121951
47  0.050697  0.186624  0.111111
48  0.189465  0.098811  0.172414
49  0.189465  0.144620  0.084746

Definig the length of each shelf:

In [5]:
len_shelf = 25
len_pass = len_shelf*2

Definig the time metrix that takes to do each type of order, by using velpcity matrix:

In [6]:
t = {"veg":[],"fru":[], "oth":[]} # A dataframe of collector's times
for i in t.keys(): # For each type of order
    for j in range(J): # For each order
        if i == "veg" or i == "fru": # Because veggies and fruits are in the same passage
            t[i].append(len_shelf/v_df[i][j])
        else: # Because others are in different passege
            t[i].append(len_pass/v_df[i][j])
t_df = pd.DataFrame(t)
t_df['Sum'] = t_df.sum(axis=1) # We will use it later and we will fix it to the real amount of time that will take to do the order
t_df

           veg         fru    oth          Sum
0   396.223298  335.564848  430.0  1161.788146
1   303.143313  637.630334  510.0  1450.773648
2   396.223298  133.959533  470.0  1000.182831
3   303.143313   96.065361  370.0   769.208674
4   303.143313  253.008578  510.0  1066.151892
5   303.143313  172.866485  410.0   886.009798
6   349.165254  253.008578  310.0   912.173832
7   303.143313  294.022555  470.0  1067.165869
8   349.165254  172.866485  490.0  1012.031739
9   396.223298  212.592458  310.0   918.815756
10  303.143313  212.592458  470.0   985.735771
11  493.125549  212.592458  470.0  1175.718007
12  349.165254  253.008578  510.0  1112.173832
13  303.143313  172.866485  510.0   986.009798
14  258.260303  212.592458  350.0   820.852761
15  258.260303  172.866485  310.0   741.126788
16  444.233423  253.008578  610.0  1307.242002
17  444.233423  133.959533  610.0  1188.192956
18  396.223298  335.564848  530.0  1261.788146
19  542.840237   96.065361  330.0   968.905598
20  214.645362  294.022555  410.0   918.667917
21  303.143313   25.000000  510.0   838.143313
22  396.223298  294.022555  410.0  1100.245853
23  172.466208  294.022555  410.0   876.488763
24  303.143313  172.866485  410.0   886.009798
25  258.260303  133.959533  530.0   922.219836
26  542.840237  133.959533  470.0  1146.799770
27  396.223298  212.592458  310.0   918.815756
28  303.143313  335.564848  450.0  1088.708162
29  444.233423  335.564848  710.0  1489.798271
30  542.840237  212.592458  350.0  1105.432695
31  214.645362  133.959533  470.0   818.604895
32  349.165254  377.581073  510.0  1236.746327
33  258.260303  253.008578  490.0  1001.268882
34  303.143313  377.581073  390.0  1070.724387
35  172.466208  172.866485  350.0   695.332693
36  303.143313  294.022555  450.0  1047.165869
37  542.840237  294.022555  490.0  1326.862792
38  493.125549  172.866485  490.0  1155.992034
39  542.840237  335.564848  510.0  1388.405085
40  349.165254   59.512056  430.0   838.677311
41  258.260303  377.581073  470.0  1105.841377
42  214.645362  133.959533  330.0   678.604895
43  396.223298  294.022555  410.0  1100.245853
44  214.645362   96.065361  350.0   660.710723
45  349.165254  462.868032  430.0  1242.033286
46  444.233423  253.008578  410.0  1107.242002
47  493.125549  133.959533  450.0  1077.085081
48  131.950791  253.008578  290.0   674.959369
49  131.950791  172.866485  590.0   894.817276

### Question no. 1

For more info, look at the docs:

In [7]:
def internal_arrangement(t_df, len_pass): # This function recives a time matrix, and we will use it for q2
    c = [0 for i in range(J)] # Definig end time matrix
    schedule = [0 for i in range(J)] # Defining the schedule for each order
    # Defining clock of the simulation
    t_now = 0 
    t_prev = 0
    for j in range(J): # For each order
        if m_df[1][j] > 0 or m_df[2][j] > 0: # If there are fruits or veggies to collect
            schedule[j] += t_now # Schedule the order for now
            t_prev = t_now 
            if m_df[1][j] > 0: # If there are veggies, collect them
                t_now += t_df["veg"][j]
            if m_df[2][j] > 0: # if ther are fruits, collect them
                t_now += t_df["fru"][j]
            if m_df[3][j] > 0: # If there are others, return back and collect them
                t_now += len_pass + t_df["oth"][j]
            t_df["Sum"][j] = t_now - t_prev # Fixing the sum collumn
            c[j] = t_now # Defining the end time of the order after all the collections
        else: # There are only others to collect
            t_now += t_df["oth"][j]
            c[j] = t_now # Defining the end time of the order after all the collections
    return c, schedule
c,schedule = internal_arrangement(t_df, len_pass)
max(c) # The answer to the question

53679.69811483437

Translating seconds to hours:

In [8]:
max(c)/(60*60)

14.911027254120658

The schedule of the orders:

In [9]:
schedule

[0,
 1211.7881463614262,
 2712.561793870506,
 3762.744624571593,
 4581.953298499368,
 5698.105190123865,
 6634.11498853765,
 7596.288820991023,
 8713.454689583788,
 9775.48642882645,
 10744.302184648564,
 11780.03795565748,
 13005.755962219484,
 14167.929794672858,
 15203.939593086645,
 16074.792354072528,
 16865.91914246328,
 18223.161143991296,
 19461.354099782704,
 20773.14224614413,
 21792.047843778637,
 22760.71576123511,
 23623.85907453719,
 24774.104927943154,
 25700.593690916492,
 26636.60348933028,
 27608.823325195135,
 28805.623094789757,
 29774.43885061187,
 30913.147012160098,
 32452.945283611843,
 33608.377978327495,
 34476.98287307909,
 35763.729200565824,
 36814.998082167294,
 37935.722468825144,
 38681.0551616195,
 39778.22103021226,
 41155.08382251176,
 42361.07585647864,
 43799.4809417336,
 44688.15825230456,
 45843.999628939375,
 46572.60452369097,
 47722.85037709693,
 48433.561099888415,
 49725.594386276665,
 50882.83638780469,
 52009.921469245666,
 52734.880838645375]

The fixed time matrix:

In [10]:
t_df

           veg         fru    oth          Sum
0   396.223298  335.564848  430.0  1211.788146
1   303.143313  637.630334  510.0  1500.773648
2   396.223298  133.959533  470.0  1050.182831
3   303.143313   96.065361  370.0   819.208674
4   303.143313  253.008578  510.0  1116.151892
5   303.143313  172.866485  410.0   936.009798
6   349.165254  253.008578  310.0   962.173832
7   303.143313  294.022555  470.0  1117.165869
8   349.165254  172.866485  490.0  1062.031739
9   396.223298  212.592458  310.0   968.815756
10  303.143313  212.592458  470.0  1035.735771
11  493.125549  212.592458  470.0  1225.718007
12  349.165254  253.008578  510.0  1162.173832
13  303.143313  172.866485  510.0  1036.009798
14  258.260303  212.592458  350.0   870.852761
15  258.260303  172.866485  310.0   791.126788
16  444.233423  253.008578  610.0  1357.242002
17  444.233423  133.959533  610.0  1238.192956
18  396.223298  335.564848  530.0  1311.788146
19  542.840237   96.065361  330.0  1018.905598
20  214.645362  294.022555  410.0   968.667917
21  303.143313   25.000000  510.0   863.143313
22  396.223298  294.022555  410.0  1150.245853
23  172.466208  294.022555  410.0   926.488763
24  303.143313  172.866485  410.0   936.009798
25  258.260303  133.959533  530.0   972.219836
26  542.840237  133.959533  470.0  1196.799770
27  396.223298  212.592458  310.0   968.815756
28  303.143313  335.564848  450.0  1138.708162
29  444.233423  335.564848  710.0  1539.798271
30  542.840237  212.592458  350.0  1155.432695
31  214.645362  133.959533  470.0   868.604895
32  349.165254  377.581073  510.0  1286.746327
33  258.260303  253.008578  490.0  1051.268882
34  303.143313  377.581073  390.0  1120.724387
35  172.466208  172.866485  350.0   745.332693
36  303.143313  294.022555  450.0  1097.165869
37  542.840237  294.022555  490.0  1376.862792
38  493.125549  172.866485  490.0  1205.992034
39  542.840237  335.564848  510.0  1438.405085
40  349.165254   59.512056  430.0   888.677311
41  258.260303  377.581073  470.0  1155.841377
42  214.645362  133.959533  330.0   728.604895
43  396.223298  294.022555  410.0  1150.245853
44  214.645362   96.065361  350.0   710.710723
45  349.165254  462.868032  430.0  1292.033286
46  444.233423  253.008578  410.0  1157.242002
47  493.125549  133.959533  450.0  1127.085081
48  131.950791  253.008578  290.0   724.959369
49  131.950791  172.866485  590.0   944.817276

### Question no. 2

For more info, look at the docs:

Definig the waiting time of all the orders:

In [11]:
w = [0 for i in range(J)]

Defining the spt algoritem function, we will use it also at question no. 2:

In [12]:
def spt_algo(t_df):
    t_now = 0
    #t_prev = t_now
    t_copy = t_df["Sum"].copy() # Creating a copy of the fixed sum column, because we don't want to lose this info
    schedule = [0 for i in range(J)] # Defining the schedule for each order
    c = [0 for i in range(J)] # Definig end time matrix, only for proving a point
    for i in range(J): # For each order
        #t_prev = t_now
        index = t_copy.idxmin() # Pull the id of the minimal processing time
        schedule[index] += t_now # Scheduling the shortest order for current time
        t_now += t_copy[index] # Moving the sim clock to the end of the order
        c[i] = t_now # Definig the end time of the order
        w[i] = c[i] - t_df["Sum"][index] # Calculating the waiting time: end time - processing time
        print("c[i]: ",c[i])
        print("t_df['Sum'][index]: ", t_df["Sum"][index])
        t_copy[index] = None # "Deleting" the minimal processing time, so we can find the next minimal time
    return schedule, c, w
sche_spt,c_spt, w = spt_algo(t_df)
sche_spt

c[i]:  710.7107227914821
t_df['Sum'][index]:  710.7107227914821
c[i]:  1435.6700921911906
t_df['Sum'][index]:  724.9593693997085
c[i]:  2164.274986942786
t_df['Sum'][index]:  728.6048947515956
c[i]:  2909.6076797371425
t_df['Sum'][index]:  745.3326927943563
c[i]:  3700.7344681278955
t_df['Sum'][index]:  791.1267883907531
c[i]:  4519.943142055671
t_df['Sum'][index]:  819.2086739277756
c[i]:  5383.086455357751
t_df['Sum'][index]:  863.1433133020801
c[i]:  6251.691350109347
t_df['Sum'][index]:  868.6048947515956
c[i]:  7122.54411109523
t_df['Sum'][index]:  870.8527609858829
c[i]:  8011.221421666188
t_df['Sum'][index]:  888.6773105709581
c[i]:  8937.710184639527
t_df['Sum'][index]:  926.4887629733385
c[i]:  9873.719983053312
t_df['Sum'][index]:  936.0097984137847
c[i]:  10809.729781467098
t_df['Sum'][index]:  936.0097984137865
c[i]:  11754.547057656093
t_df['Sum'][index]:  944.8172761889946
c[i]:  12716.720890109467
t_df['Sum'][index]:  962.1738324533735
c[i]:  13685.388807565942
t_df['Sum'][index]:  968.6679174564742
c[i]:  14654.204563388055
t_df['Sum'][index]:  968.8157558221137
c[i]:  15623.020319210169
t_df['Sum'][index]:  968.8157558221137
c[i]:  16595.240155075026
t_df['Sum'][index]:  972.2198358648566
c[i]:  17614.145752709534
t_df['Sum'][index]:  1018.905597634508
c[i]:  18649.88152371845
t_df['Sum'][index]:  1035.7357710089163
c[i]:  19685.891322132236
t_df['Sum'][index]:  1036.0097984137865
c[i]:  20736.074152833324
t_df['Sum'][index]:  1050.182830701087
c[i]:  21787.343034434794
t_df['Sum'][index]:  1051.2688816014706
c[i]:  22849.374773677457
t_df['Sum'][index]:  1062.0317392426623
c[i]:  23946.540642270218
t_df['Sum'][index]:  1097.1658685927614
c[i]:  25062.692533894715
t_df['Sum'][index]:  1116.1518916244968
c[i]:  26179.85840248748
t_df['Sum'][index]:  1117.165868592765
c[i]:  27300.58278914533
t_df['Sum'][index]:  1120.7243866578501
c[i]:  28427.66787058631
t_df['Sum'][index]:  1127.0850814409787
c[i]:  29566.376032134536
t_df['Sum'][index]:  1138.7081615482275
c[i]:  30716.6218855405
t_df['Sum'][index]:  1150.2458534059624
c[i]:  31866.86773894646
t_df['Sum'][index]:  1150.2458534059624
c[i]:  33022.30043366211
t_df['Sum'][index]:  1155.4326947156515
c[i]:  34178.141810296926
t_df['Sum'][index]:  1155.8413766348167
c[i]:  35335.38381182495
t_df['Sum'][index]:  1157.2420015280222
c[i]:  36497.55764427832
t_df['Sum'][index]:  1162.1738324533744
c[i]:  37694.357413872945
t_df['Sum'][index]:  1196.7997695946215
c[i]:  38900.34944783982
t_df['Sum'][index]:  1205.9920339668752
c[i]:  40112.137594201246
t_df['Sum'][index]:  1211.7881463614262
c[i]:  41337.85560076325
t_df['Sum'][index]:  1225.7180065620032
c[i]:  42576.048556554655
t_df['Sum'][index]:  1238.1929557914082
c[i]:  43862.79488404139
t_df['Sum'][index]:  1286.7463274867332
c[i]:  45154.82817042964
t_df['Sum'][index]:  1292.0332863882504
c[i]:  46466.61631679106
t_df['Sum'][index]:  1311.7881463614249
c[i]:  47823.85831831908
t_df['Sum'][index]:  1357.242001528015
c[i]:  49200.72111061858
t_df['Sum'][index]:  1376.8627922995001
c[i]:  50639.12619587354
t_df['Sum'][index]:  1438.4050852549626
c[i]:  52139.89984338262
t_df['Sum'][index]:  1500.7736475090796
c[i]:  53679.69811483436
t_df['Sum'][index]:  1539.7982714517457

[38900.34944783982,
 50639.12619587354,
 19685.891322132236,
 3700.7344681278955,
 23946.540642270218,
 8937.710184639527,
 11754.547057656093,
 25062.692533894715,
 21787.343034434794,
 13685.388807565942,
 17614.145752709534,
 40112.137594201246,
 35335.38381182495,
 18649.88152371845,
 6251.691350109347,
 2909.6076797371425,
 46466.61631679106,
 41337.85560076325,
 45154.82817042964,
 16595.240155075026,
 12716.720890109467,
 4519.943142055671,
 29566.376032134536,
 8011.221421666188,
 9873.719983053312,
 15623.020319210169,
 36497.55764427832,
 14654.204563388055,
 28427.66787058631,
 52139.89984338262,
 31866.86773894646,
 5383.086455357751,
 42576.048556554655,
 20736.074152833324,
 26179.85840248748,
 2164.274986942786,
 22849.374773677457,
 47823.85831831908,
 37694.357413872945,
 49200.72111061858,
 7122.54411109523,
 33022.30043366211,
 1435.6700921911906,
 30716.6218855405,
 0,
 43862.79488404139,
 34178.141810296926,
 27300.58278914533,
 710.7107227914821,
 10809.729781467098]

Note: We will use sche_spt in question 3.

The waiting time matrix:

In [13]:
w

[0.0,
 710.7107227914821,
 1435.6700921911906,
 2164.274986942786,
 2909.6076797371425,
 3700.7344681278955,
 4519.943142055671,
 5383.086455357751,
 6251.691350109347,
 7122.54411109523,
 8011.221421666189,
 8937.710184639527,
 9873.719983053312,
 10809.729781467098,
 11754.547057656095,
 12716.720890109467,
 13685.388807565942,
 14654.204563388055,
 15623.020319210169,
 16595.240155075026,
 17614.145752709534,
 18649.88152371845,
 19685.891322132236,
 20736.074152833324,
 21787.343034434794,
 22849.374773677457,
 23946.540642270218,
 25062.692533894715,
 26179.85840248748,
 27300.58278914533,
 28427.66787058631,
 29566.376032134536,
 30716.6218855405,
 31866.867738946457,
 33022.30043366211,
 34178.141810296926,
 35335.38381182495,
 36497.55764427832,
 37694.357413872945,
 38900.34944783982,
 40112.137594201246,
 41337.85560076324,
 42576.048556554655,
 43862.79488404139,
 45154.82817042964,
 46466.61631679106,
 47823.85831831908,
 49200.72111061858,
 50639.12619587354,
 52139.89984338262]

The proof that c isn't dependent on the scheduling of the order:

In [14]:
max(c_spt)

53679.69811483436

The average waiting time for order:

In [15]:
sum(w)/J

23523.83323559002

### Question no. 3

First, we will calculate v and t for the new collector:

In [16]:
v2_df = v_df.copy()
v2_df = v2_df*1.15
v2_df

         veg       fru       oth
0   0.072560  0.085676  0.133721
1   0.094840  0.045089  0.112745
2   0.072560  0.214617  0.122340
3   0.094840  0.299275  0.155405
4   0.094840  0.113633  0.112745
5   0.094840  0.166313  0.140244
6   0.082339  0.113633  0.185484
7   0.094840  0.097782  0.122340
8   0.082339  0.166313  0.117347
9   0.072560  0.135235  0.185484
10  0.094840  0.135235  0.122340
11  0.058302  0.135235  0.122340
12  0.082339  0.113633  0.112745
13  0.094840  0.166313  0.112745
14  0.111322  0.135235  0.164286
15  0.111322  0.166313  0.185484
16  0.064718  0.113633  0.094262
17  0.064718  0.214617  0.094262
18  0.072560  0.085676  0.108491
19  0.052962  0.299275  0.174242
20  0.133942  0.097782  0.140244
21  0.094840  1.150000  0.112745
22  0.072560  0.097782  0.140244
23  0.166699  0.097782  0.140244
24  0.094840  0.166313  0.140244
25  0.111322  0.214617  0.108491
26  0.052962  0.214617  0.122340
27  0.072560  0.135235  0.185484
28  0.094840  0.085676  0.127778
29  0.064718  0.085676  0.080986
30  0.052962  0.135235  0.164286
31  0.133942  0.214617  0.122340
32  0.082339  0.076143  0.112745
33  0.111322  0.113633  0.117347
34  0.094840  0.076143  0.147436
35  0.166699  0.166313  0.164286
36  0.094840  0.097782  0.127778
37  0.052962  0.097782  0.117347
38  0.058302  0.166313  0.117347
39  0.052962  0.085676  0.112745
40  0.082339  0.483095  0.133721
41  0.111322  0.076143  0.122340
42  0.133942  0.214617  0.174242
43  0.072560  0.097782  0.140244
44  0.133942  0.299275  0.164286
45  0.082339  0.062113  0.133721
46  0.064718  0.113633  0.140244
47  0.058302  0.214617  0.127778
48  0.217884  0.113633  0.198276
49  0.217884  0.166313  0.097458

In [17]:
t2 = {"veg":[],"fru":[], "oth":[]}
for i in t2.keys():
    for j in range(J):
        if i == "veg" or i == "fru":
            t2[i].append(len_shelf/v2_df[i][j])
        else:
            t2[i].append(len_pass/v2_df[i][j])
t2_df = pd.DataFrame(t2)
t2_df['Sum'] = t2_df.sum(axis=1)
t2_df

           veg         fru         oth          Sum
0   344.541998  291.795520  373.913043  1010.250562
1   263.602881  554.461160  443.478261  1261.542302
2   344.541998  116.486550  408.695652   869.724201
3   263.602881   83.535096  321.739130   668.877108
4   263.602881  220.007459  443.478261   927.088601
5   263.602881  150.318683  356.521739   770.443303
6   303.621960  220.007459  269.565217   793.194637
7   263.602881  255.671787  408.695652   927.970321
8   303.621960  150.318683  426.086957   880.027599
9   344.541998  184.863007  269.565217   798.970222
10  263.602881  184.863007  408.695652   857.161540
11  428.804825  184.863007  408.695652  1022.363484
12  303.621960  220.007459  443.478261   967.107680
13  263.602881  150.318683  443.478261   857.399825
14  224.574177  184.863007  304.347826   713.785010
15  224.574177  150.318683  269.565217   644.458077
16  386.289933  220.007459  530.434783  1136.732175
17  386.289933  116.486550  530.434783  1033.211266
18  344.541998  291.795520  460.869565  1097.207084
19  472.034989   83.535096  286.956522   842.526607
20  186.648141  255.671787  356.521739   798.841667
21  263.602881   21.739130  443.478261   728.820272
22  344.541998  255.671787  356.521739   956.735525
23  149.970615  255.671787  356.521739   762.164142
24  263.602881  150.318683  356.521739   770.443303
25  224.574177  116.486550  460.869565   801.930292
26  472.034989  116.486550  408.695652   997.217191
27  344.541998  184.863007  269.565217   798.970222
28  263.602881  291.795520  391.304348   946.702749
29  386.289933  291.795520  617.391304  1295.476758
30  472.034989  184.863007  304.347826   961.245821
31  186.648141  116.486550  408.695652   711.830343
32  303.621960  328.331368  443.478261  1075.431589
33  224.574177  220.007459  426.086957   870.668593
34  263.602881  328.331368  339.130435   931.064684
35  149.970615  150.318683  304.347826   604.637124
36  263.602881  255.671787  391.304348   910.579016
37  472.034989  255.671787  426.086957  1153.793732
38  428.804825  150.318683  426.086957  1005.210464
39  472.034989  291.795520  443.478261  1207.308770
40  303.621960   51.749614  373.913043   729.284618
41  224.574177  328.331368  408.695652   961.601197
42  186.648141  116.486550  286.956522   590.091213
43  344.541998  255.671787  356.521739   956.735525
44  186.648141   83.535096  304.347826   574.531063
45  303.621960  402.493941  373.913043  1080.028945
46  386.289933  220.007459  356.521739   962.819132
47  428.804825  116.486550  391.304348   936.595723
48  114.739818  220.007459  252.173913   586.921191
49  114.739818  150.318683  513.043478   778.101979

In [18]:
internal_arrangement(t2_df, len_pass = len_pass/1.15)
spt_algo(t2_df)
t2_df

c[i]:  618.0093241665018
t_df['Sum'][index]:  618.0093241665018
c[i]:  1248.4087758184178
t_df['Sum'][index]:  630.399451651916
c[i]:  1881.9782495154577
t_df['Sum'][index]:  633.5694736970399
c[i]:  2530.093634554025
t_df['Sum'][index]:  648.1153850385672
c[i]:  3218.029972285114
t_df['Sum'][index]:  687.9363377310892
c[i]:  3930.3853409179624
t_df['Sum'][index]:  712.3553686328482
c[i]:  4680.944743789338
t_df['Sum'][index]:  750.5594028713749
c[i]:  5436.253347921162
t_df['Sum'][index]:  755.3086041318238
c[i]:  6193.516618343669
t_df['Sum'][index]:  757.263270422507
c[i]:  6966.279497101024
t_df['Sum'][index]:  772.7628787573558
c[i]:  7771.921899686537
t_df['Sum'][index]:  805.6424025855122
c[i]:  8585.84346352461
t_df['Sum'][index]:  813.9215638380738
c[i]:  9399.765027362684
t_df['Sum'][index]:  813.9215638380738
c[i]:  10221.345267527022
t_df['Sum'][index]:  821.5802401643377
c[i]:  11058.018165312566
t_df['Sum'][index]:  836.6728977855428
c[i]:  11900.338093535585
t_df['Sum'][index]:  842.3199282230198
c[i]:  12742.786576859162
t_df['Sum'][index]:  842.4484833235765
c[i]:  13585.23506018274
t_df['Sum'][index]:  842.4484833235783
c[i]:  14430.643613108701
t_df['Sum'][index]:  845.408552925961
c[i]:  15316.64848061697
t_df['Sum'][index]:  886.004867508269
c[i]:  16217.288281494288
t_df['Sum'][index]:  900.6398008773176
c[i]:  17118.16636707149
t_df['Sum'][index]:  900.8780855772038
c[i]:  18031.368828550698
t_df['Sum'][index]:  913.2024614792062
c[i]:  18945.515682117188
t_df['Sum'][index]:  914.1468535664899
c[i]:  19869.0215423282
t_df['Sum'][index]:  923.5058602110093
c[i]:  20823.078819365393
t_df['Sum'][index]:  954.0572770371946
c[i]:  21793.645681647566
t_df['Sum'][index]:  970.5668622821718
c[i]:  22765.094263032577
t_df['Sum'][index]:  971.4485813850124
c[i]:  23739.63720795245
t_df['Sum'][index]:  974.5429449198746
c[i]:  24719.711191814175
t_df['Sum'][index]:  980.0739838617228
c[i]:  25709.89220185611
t_df['Sum'][index]:  990.1810100419352
c[i]:  26710.105987426512
t_df['Sum'][index]:  1000.2137855704023
c[i]:  27710.319772996918
t_df['Sum'][index]:  1000.2137855704059
c[i]:  28715.04385535835
t_df['Sum'][index]:  1004.7240823614338
c[i]:  29720.123313301672
t_df['Sum'][index]:  1005.0794579433204
c[i]:  30726.42070593473
t_df['Sum'][index]:  1006.2973926330596
c[i]:  31737.006647198534
t_df['Sum'][index]:  1010.5859412638019
c[i]:  32777.702099019945
t_df['Sum'][index]:  1040.6954518214116
c[i]:  33826.39082420853
t_df['Sum'][index]:  1048.6887251885855
c[i]:  34880.11964713151
t_df['Sum'][index]:  1053.7288229229794
c[i]:  35945.96139196804
t_df['Sum'][index]:  1065.8417448365253
c[i]:  37022.65091874318
t_df['Sum'][index]:  1076.6895267751388
c[i]:  38141.560768731644
t_df['Sum'][index]:  1118.909849988464
c[i]:  39265.06797428664
t_df['Sum'][index]:  1123.5072055549972
c[i]:  40405.753318948744
t_df['Sum'][index]:  1140.6853446621062
c[i]:  41585.96375506006
t_df['Sum'][index]:  1180.210436111318
c[i]:  42783.23574836397
t_df['Sum'][index]:  1197.2719933039116
c[i]:  44034.02277902046
t_df['Sum'][index]:  1250.7870306564873
c[i]:  45339.04334207183
t_df['Sum'][index]:  1305.0205630513733
c[i]:  46677.99836072553
t_df['Sum'][index]:  1338.9550186536908

           veg         fru         oth          Sum
0   344.541998  291.795520  373.913043  1053.728823
1   263.602881  554.461160  443.478261  1305.020563
2   344.541998  116.486550  408.695652   913.202461
3   263.602881   83.535096  321.739130   712.355369
4   263.602881  220.007459  443.478261   970.566862
5   263.602881  150.318683  356.521739   813.921564
6   303.621960  220.007459  269.565217   836.672898
7   263.602881  255.671787  408.695652   971.448581
8   303.621960  150.318683  426.086957   923.505860
9   344.541998  184.863007  269.565217   842.448483
10  263.602881  184.863007  408.695652   900.639801
11  428.804825  184.863007  408.695652  1065.841745
12  303.621960  220.007459  443.478261  1010.585941
13  263.602881  150.318683  443.478261   900.878086
14  224.574177  184.863007  304.347826   757.263270
15  224.574177  150.318683  269.565217   687.936338
16  386.289933  220.007459  530.434783  1180.210436
17  386.289933  116.486550  530.434783  1076.689527
18  344.541998  291.795520  460.869565  1140.685345
19  472.034989   83.535096  286.956522   886.004868
20  186.648141  255.671787  356.521739   842.319928
21  263.602881   21.739130  443.478261   750.559403
22  344.541998  255.671787  356.521739  1000.213786
23  149.970615  255.671787  356.521739   805.642403
24  263.602881  150.318683  356.521739   813.921564
25  224.574177  116.486550  460.869565   845.408553
26  472.034989  116.486550  408.695652  1040.695452
27  344.541998  184.863007  269.565217   842.448483
28  263.602881  291.795520  391.304348   990.181010
29  386.289933  291.795520  617.391304  1338.955019
30  472.034989  184.863007  304.347826  1004.724082
31  186.648141  116.486550  408.695652   755.308604
32  303.621960  328.331368  443.478261  1118.909850
33  224.574177  220.007459  426.086957   914.146854
34  263.602881  328.331368  339.130435   974.542945
35  149.970615  150.318683  304.347826   648.115385
36  263.602881  255.671787  391.304348   954.057277
37  472.034989  255.671787  426.086957  1197.271993
38  428.804825  150.318683  426.086957  1048.688725
39  472.034989  291.795520  443.478261  1250.787031
40  303.621960   51.749614  373.913043   772.762879
41  224.574177  328.331368  408.695652  1005.079458
42  186.648141  116.486550  286.956522   633.569474
43  344.541998  255.671787  356.521739  1000.213786
44  186.648141   83.535096  304.347826   618.009324
45  303.621960  402.493941  373.913043  1123.507206
46  386.289933  220.007459  356.521739  1006.297393
47  428.804825  116.486550  391.304348   980.073984
48  114.739818  220.007459  252.173913   630.399452
49  114.739818  150.318683  513.043478   821.580240

prep for Q//c_max - for more info go to doc:

calc the ratio of the task index (K) to the working rate of the gatherer (s_j: s1 = 1, s2 = 1.15): K/s_j

In [19]:
K_S1 = [i for i in range(1, J+1)]

K_S2 = [0 for i in range(1, J+1)]
for i in range(1, 51):
    K_S2[i-1] = i/1.15

As we do in Q//sigma(C_i): take the task with the longest time and match it to the min ratio of both gatherers.
The heuristics will be to place the tasks from the beginning and not the end (as we do in P//c_max). 

* Note the longest task will be the same for the both gatherers since the ratio is permanent

In [20]:
#initializing schedules: 1 for the regular, 2 for the faster one
sch_1 = []
sch_2 = []

#initializing time counters
time_1 = 0
time_2 = 0

# for Q4 - initializing dictionaries for waiting time to each task in specific gather. 
waiting_time_1 = {}
waiting_time_2 = {}

#copy for processing times
t_df_copy = t_df.copy()


for i in range(J):
    #print('----------------------------------------------------')
    #print(i)
    task_idx = t_df_copy['Sum'].idxmax() # task index with max time
    task_time_1 = t_df_copy['Sum'][task_idx] # time processing for the regular
    task_time_2 = t2_df['Sum'][task_idx] ## time processing for the fast gather
    #print('task_time_1 ', task_time_1)
    #print('task_time_2 ', task_time_2)
    
    t_df_copy['Sum'][task_idx] = None # for not using it again
    
    # taking min ratio
    min_K_S1 = min(K_S1)
    min_K_S2 = min(K_S2)
    
    min_tot = 0
    
    #case the min ratio is for the regular gather
    if min_K_S1 < min_K_S2:
        waiting_time_1[task_idx] = time_1 # waiting time until now, not including the process time for this task
        min_tot = min_K_S1
        idx = K_S1.index(min_tot)
        K_S1.pop(idx)
            
        sch_1.append(task_idx) # add the task to regular gather schedule
            
        time_1 += task_time_1 # update time
        #print('m is: 1')
    
    #case the min ratio is for the fast gather    
    else:
        waiting_time_2[task_idx] = time_2 # waiting time until now, not including the process time for this task
        min_tot = min_K_S2
        idx = K_S2.index(min_tot)
        K_S2.pop(idx)
            
        sch_2.append(task_idx) # add the task to faster gather schedule
            
        time_2 += task_time_2 # update time
        #print('m is: 2')
        
    #print('time_1 ', time_1)
    #print('time_2 ', time_2)
    #print('sch_1 is: ', sch_1)
    #print('sch_2 is: ', sch_2)
    #print('----------------------------------------------------')

time_finish = max(time_2, time_1) # C_MAX

print('time_finish: ',time_finish)
print('sch for regular gather: ', sch_1)
print('sch for fast gather: ', sch_2)

time_finish:  25179.705672488097
sch for regular gather:  [1, 37, 18, 32, 11, 38, 46, 30, 43, 47, 7, 36, 33, 10, 25, 27, 6, 24, 23, 31, 3, 35, 48]
sch for fast gather:  [29, 39, 16, 45, 17, 0, 26, 12, 41, 22, 28, 34, 4, 8, 2, 13, 19, 9, 20, 49, 5, 40, 14, 21, 15, 42, 44]

In [21]:
#print('waiting_time for 1: ', waiting_time_1.items())
total_wt_1 = sum(list(waiting_time_1.values()))
avg_wt_1 = total_wt_1/len(list(waiting_time_1.values()))
print('total_wt_regular: ', total_wt_1)
print('avg_wt_regular: ', avg_wt_1)

print('-----------------------------------------------------')

#print('waiting_time for 2: ', waiting_time_2.items())
total_wt_2 = sum(list(waiting_time_2.values()))
avg_wt_2 = total_wt_2/len(list(waiting_time_2.values()))
print('total_wt_fast: ', total_wt_2)
print('avg_wt_fast: ',avg_wt_2)

print('-----------------------------------------------------')

total_wt_both = total_wt_1 + total_wt_2
avg_wt__both = total_wt_both/J
print('total_wt_both: ', total_wt_both)
print('avg_wt__both: ',avg_wt__both)

total_wt_regular:  300799.9876541074
avg_wt_regular:  13078.260332787278
-----------------------------------------------------
total_wt_fast:  363065.66825086775
avg_wt_fast:  13446.87660188399
-----------------------------------------------------
total_wt_both:  663865.6559049751
avg_wt__both:  13277.313118099502

### Question no. 4

In [23]:
pass

### Question no. 5

In [24]:
pass

### Question no. 6

In [25]:
pass