## Production Systems Analysis Project
Owners: Almog Asraf, Daniel Pidtylok, Nir Levanon, Shani Yorav

### Imports

In [248]:
import numpy as np
import pandas as pd

### Parameters

In [249]:
J = 50 # Numbers of the orders

Creating the amount of vegtables, fruits and others from poission destribution:

In [250]:
lamb = [7.5, 5.2, 20] # Lambdas for the poission destribution
m = {1:[],2:[],3:[]} # 1: veggies, 2: fruits, 3: other
for i in m.keys(): # For each type of order
    for j in range(J): # For each order
        m[i].append(np.random.poisson(lamb[i-1]))
m_df = pd.DataFrame(m) # More easy to work with pandas df
m_df

     1  2   3
0    9  9  27
1    6  5  26
2    9  4  20
3    4  4  11
4    8  7  19
5    9  5  22
6   12  1  18
7    9  7  24
8    4  4  15
9    6  2  21
10   5  5  22
11  14  8  23
12   9  4  20
13   8  9  27
14   6  5  14
15   8  5  17
16   7  8  16
17   9  5  17
18   4  3  20
19  11  7  30
20   8  3  21
21  11  4  18
22   5  4  22
23   4  3  13
24   6  8  23
25   9  9  14
26   9  6  17
27   5  4  15
28  11  4  18
29   4  5  22
30   3  5  16
31   6  6  28
32   7  3  25
33   7  4  18
34   5  3  23
35   8  9  18
36   7  6  19
37  11  2  28
38   5  3  16
39  10  1  16
40  11  6  26
41   6  5  27
42  13  5  24
43   7  5  20
44  13  3  18
45   7  2  19
46   6  5  25
47  10  8  20
48   3  6  22
49   7  6  21

Creating the velocity matrix for each order:

In [251]:
v = {"veg":[],"fru":[], "oth":[]} # A dataframe of collector's velocity
for i in v.keys(): # For each type of order
    for j in range(J): # For each order
        if i == "veg":
            v[i].append((25/(25+25*m[1][j]))**1.2)
        elif i == "fru":
            v[i].append((25/(25+30*m[2][j]))**1.1)
        else:
            v[i].append(25/(25+10*m[3][j]))
v_df = pd.DataFrame(v) # More easy to work with pandas
v_df

         veg       fru       oth
0   0.063096  0.066211  0.084746
1   0.096802  0.117596  0.087719
2   0.063096  0.144620  0.111111
3   0.144956  0.144620  0.185185
4   0.071599  0.085027  0.116279
5   0.063096  0.117596  0.102041
6   0.046054  0.420083  0.121951
7   0.063096  0.085027  0.094340
8   0.144956  0.144620  0.142857
9   0.096802  0.260239  0.106383
10  0.116471  0.117596  0.102041
11  0.038787  0.074501  0.098039
12  0.063096  0.144620  0.111111
13  0.071599  0.066211  0.084746
14  0.096802  0.117596  0.151515
15  0.071599  0.117596  0.128205
16  0.082469  0.074501  0.135135
17  0.063096  0.117596  0.128205
18  0.144956  0.186624  0.111111
19  0.050697  0.085027  0.076923
20  0.071599  0.186624  0.106383
21  0.050697  0.144620  0.121951
22  0.116471  0.144620  0.102041
23  0.144956  0.186624  0.161290
24  0.096802  0.074501  0.098039
25  0.063096  0.066211  0.151515
26  0.063096  0.098811  0.128205
27  0.116471  0.144620  0.142857
28  0.050697  0.144620  0.121951
29  0.144956  0.117596  0.102041
30  0.189465  0.117596  0.135135
31  0.096802  0.098811  0.081967
32  0.082469  0.186624  0.090909
33  0.082469  0.144620  0.121951
34  0.116471  0.186624  0.098039
35  0.071599  0.066211  0.121951
36  0.082469  0.098811  0.116279
37  0.050697  0.260239  0.081967
38  0.116471  0.186624  0.135135
39  0.056277  0.420083  0.135135
40  0.050697  0.098811  0.087719
41  0.096802  0.117596  0.084746
42  0.042135  0.117596  0.094340
43  0.082469  0.117596  0.111111
44  0.042135  0.186624  0.121951
45  0.082469  0.260239  0.116279
46  0.096802  0.117596  0.090909
47  0.056277  0.074501  0.111111
48  0.189465  0.098811  0.102041
49  0.082469  0.098811  0.106383

Definig the length of each shelf:

In [252]:
len_shelf = 25
len_pass = len_shelf*2

Definig the time metrix that takes to do each type of order, by using velpcity matrix:

In [253]:
t = {"veg":[],"fru":[], "oth":[]} # A dataframe of collector's times
for i in t.keys(): # For each type of order
    for j in range(J): # For each order
        if i == "veg" or i == "fru": # Because veggies and fruits are in the same passage
            t[i].append(len_shelf/v_df[i][j])
        else: # Because others are in different passege
            t[i].append(len_pass/v_df[i][j])
t_df = pd.DataFrame(t)
t_df['Sum'] = t_df.sum(axis=1) # We will use it later and we will fix it to the real amount of time that will take to do the order
t_df

           veg         fru    oth          Sum
0   396.223298  377.581073  590.0  1363.804371
1   258.260303  212.592458  570.0  1040.852761
2   396.223298  172.866485  450.0  1019.089783
3   172.466208  172.866485  270.0   615.332693
4   349.165254  294.022555  430.0  1073.187809
5   396.223298  212.592458  490.0  1098.815756
6   542.840237   59.512056  410.0  1012.352293
7   396.223298  294.022555  530.0  1220.245853
8   172.466208  172.866485  350.0   695.332693
9   258.260303   96.065361  470.0   824.325664
10  214.645362  212.592458  490.0   917.237820
11  644.539473  335.564848  510.0  1490.104321
12  396.223298  172.866485  450.0  1019.089783
13  349.165254  377.581073  590.0  1316.746327
14  258.260303  212.592458  330.0   800.852761
15  349.165254  212.592458  390.0   951.757712
16  303.143313  335.564848  370.0  1008.708162
17  396.223298  212.592458  390.0   998.815756
18  172.466208  133.959533  450.0   756.425740
19  493.125549  294.022555  650.0  1437.148104
20  349.165254  133.959533  470.0   953.124787
21  493.125549  172.866485  410.0  1075.992034
22  214.645362  172.866485  490.0   877.511847
23  172.466208  133.959533  310.0   616.425740
24  258.260303  335.564848  510.0  1103.825152
25  396.223298  377.581073  330.0  1103.804371
26  396.223298  253.008578  390.0  1039.231876
27  214.645362  172.866485  350.0   737.511847
28  493.125549  172.866485  410.0  1075.992034
29  172.466208  212.592458  490.0   875.058665
30  131.950791  212.592458  370.0   714.543249
31  258.260303  253.008578  610.0  1121.268882
32  303.143313  133.959533  550.0   987.102846
33  303.143313  172.866485  410.0   886.009798
34  214.645362  133.959533  510.0   858.604895
35  349.165254  377.581073  410.0  1136.746327
36  303.143313  253.008578  430.0   986.151892
37  493.125549   96.065361  610.0  1199.190909
38  214.645362  133.959533  370.0   718.604895
39  444.233423   59.512056  370.0   873.745480
40  493.125549  253.008578  570.0  1316.134127
41  258.260303  212.592458  590.0  1060.852761
42  593.326371  212.592458  530.0  1335.918829
43  303.143313  212.592458  450.0   965.735771
44  593.326371  133.959533  410.0  1137.285904
45  303.143313   96.065361  430.0   829.208674
46  258.260303  212.592458  550.0  1020.852761
47  444.233423  335.564848  450.0  1229.798271
48  131.950791  253.008578  490.0   874.959369
49  303.143313  253.008578  470.0  1026.151892

### Question no. 1

For more info, look at the docs:

In [254]:
def internal_arrangement(t_df, len_pass): # This function recives a time matrix, and we will use it for q2
    c = [0 for i in range(J)] # Definig end time matrix
    schedule = [0 for i in range(J)] # Defining the schedule for each order
    # Defining clock of the simulation
    t_now = 0 
    t_prev = 0
    for j in range(J): # For each order
        if m_df[1][j] > 0 or m_df[2][j] > 0: # If there are fruits or veggies to collect
            schedule[j] += t_now # Schedule the order for now
            t_prev = t_now 
            #if m_df[1][j] > 0: # If there are veggies, collect them
            t_now += t_df["veg"][j]
            #if m_df[2][j] > 0: # if ther are fruits, collect them
            t_now += t_df["fru"][j]
            if m_df[3][j] > 0: # If there are others, return back and collect them
                t_now += len_pass + t_df["oth"][j]
            t_df["Sum"][j] = t_now - t_prev # Fixing the sum collumn
            c[j] = t_now # Defining the end time of the order after all the collections
        else: # There are only others to collect
            t_now += t_df["oth"][j]
            c[j] = t_now # Defining the end time of the order after all the collections
    return c, schedule
c,schedule = internal_arrangement(t_df, len_pass)
max(c) # The answer to the question

52897.57204929294

Translating seconds to hours:

In [255]:
max(c)/(60*60)

14.693770013692482

The schedule of the orders:

In [256]:
schedule

[0,
 1413.8043714710536,
 2504.657132456937,
 3573.7469156839206,
 4239.079608478278,
 5362.267417899919,
 6511.083173722034,
 7573.435467170856,
 8843.68132057682,
 9589.014013371177,
 10463.33967727592,
 11430.577497148544,
 12970.681818239997,
 14039.771601466982,
 15406.517928953714,
 16257.370689939597,
 17259.128401777387,
 18317.836563325614,
 19366.652319147728,
 20173.07805941619,
 21660.226163562045,
 22663.35095027881,
 23789.342984245686,
 24716.854831523182,
 25383.280571791645,
 26537.10572331684,
 27690.91009478789,
 28780.141971225585,
 29567.65381850308,
 30693.645852469956,
 31618.704517859445,
 32383.24776664357,
 33554.51664824504,
 34591.61949413292,
 35527.629292546706,
 36436.2341872983,
 37622.98051478503,
 38659.132406409524,
 39908.32331589039,
 40676.928210641985,
 41600.67369028759,
 42966.80781746518,
 44077.66057845106,
 45463.57940723325,
 46479.31517824216,
 47666.601081903325,
 48545.8097558311,
 49616.662516816985,
 50896.460788268734,
 51821.42015766844]

The fixed time matrix:

In [257]:
t_df

           veg         fru    oth          Sum
0   396.223298  377.581073  590.0  1413.804371
1   258.260303  212.592458  570.0  1090.852761
2   396.223298  172.866485  450.0  1069.089783
3   172.466208  172.866485  270.0   665.332693
4   349.165254  294.022555  430.0  1123.187809
5   396.223298  212.592458  490.0  1148.815756
6   542.840237   59.512056  410.0  1062.352293
7   396.223298  294.022555  530.0  1270.245853
8   172.466208  172.866485  350.0   745.332693
9   258.260303   96.065361  470.0   874.325664
10  214.645362  212.592458  490.0   967.237820
11  644.539473  335.564848  510.0  1540.104321
12  396.223298  172.866485  450.0  1069.089783
13  349.165254  377.581073  590.0  1366.746327
14  258.260303  212.592458  330.0   850.852761
15  349.165254  212.592458  390.0  1001.757712
16  303.143313  335.564848  370.0  1058.708162
17  396.223298  212.592458  390.0  1048.815756
18  172.466208  133.959533  450.0   806.425740
19  493.125549  294.022555  650.0  1487.148104
20  349.165254  133.959533  470.0  1003.124787
21  493.125549  172.866485  410.0  1125.992034
22  214.645362  172.866485  490.0   927.511847
23  172.466208  133.959533  310.0   666.425740
24  258.260303  335.564848  510.0  1153.825152
25  396.223298  377.581073  330.0  1153.804371
26  396.223298  253.008578  390.0  1089.231876
27  214.645362  172.866485  350.0   787.511847
28  493.125549  172.866485  410.0  1125.992034
29  172.466208  212.592458  490.0   925.058665
30  131.950791  212.592458  370.0   764.543249
31  258.260303  253.008578  610.0  1171.268882
32  303.143313  133.959533  550.0  1037.102846
33  303.143313  172.866485  410.0   936.009798
34  214.645362  133.959533  510.0   908.604895
35  349.165254  377.581073  410.0  1186.746327
36  303.143313  253.008578  430.0  1036.151892
37  493.125549   96.065361  610.0  1249.190909
38  214.645362  133.959533  370.0   768.604895
39  444.233423   59.512056  370.0   923.745480
40  493.125549  253.008578  570.0  1366.134127
41  258.260303  212.592458  590.0  1110.852761
42  593.326371  212.592458  530.0  1385.918829
43  303.143313  212.592458  450.0  1015.735771
44  593.326371  133.959533  410.0  1187.285904
45  303.143313   96.065361  430.0   879.208674
46  258.260303  212.592458  550.0  1070.852761
47  444.233423  335.564848  450.0  1279.798271
48  131.950791  253.008578  490.0   924.959369
49  303.143313  253.008578  470.0  1076.151892

### Question no. 2

For more info, look at the docs:

Definig the waiting time of all the orders:

In [258]:
w = [0 for i in range(J)]

Defining the spt algoritem function, we will use it also at question no. 2:

In [259]:
def spt_algo(t_df):
    t_now = 0
    #t_prev = t_now
    t_copy = t_df["Sum"].copy() # Creating a copy of the fixed sum column, because we don't want to lose this info
    schedule = [0 for i in range(J)] # Defining the schedule for each order
    c = [0 for i in range(J)] # Definig end time matrix, only for proving a point
    for i in range(J): # For each order
        #t_prev = t_now
        index = t_copy.idxmin() # Pull the id of the minimal processing time
        schedule[index] += t_now # Scheduling the shortest order for current time
        t_now += t_copy[index] # Moving the sim clock to the end of the order
        c[i] = t_now # Definig the end time of the order
        w[i] = c[i] - t_df["Sum"][index] # Calculating the waiting time: end time - processing time
        print("c[i]: ",c[i])
        print("t_df['Sum'][index]: ", t_df["Sum"][index])
        t_copy[index] = None # "Deleting" the minimal processing time, so we can find the next minimal time
    return schedule, c, w
sche_spt,c_spt, w = spt_algo(t_df)
sche_spt

c[i]:  665.3326927943572
t_df['Sum'][index]:  665.3326927943572
c[i]:  1331.7584330628206
t_df['Sum'][index]:  666.4257402684634
c[i]:  2077.0911258571787
t_df['Sum'][index]:  745.3326927943581
c[i]:  2841.634374641303
t_df['Sum'][index]:  764.5432487841244
c[i]:  3610.2392693928987
t_df['Sum'][index]:  768.6048947515956
c[i]:  4397.751116670394
t_df['Sum'][index]:  787.5118472774957
c[i]:  5204.176856938858
t_df['Sum'][index]:  806.4257402684634
c[i]:  6055.029617924741
t_df['Sum'][index]:  850.8527609858829
c[i]:  6929.355281829484
t_df['Sum'][index]:  874.3256639047431
c[i]:  7808.563955757257
t_df['Sum'][index]:  879.2086739277729
c[i]:  8717.168850508853
t_df['Sum'][index]:  908.6048947515956
c[i]:  9640.914330154461
t_df['Sum'][index]:  923.7454796456077
c[i]:  10565.87369955417
t_df['Sum'][index]:  924.9593693997085
c[i]:  11490.93236494366
t_df['Sum'][index]:  925.0586653894898
c[i]:  12418.444212221155
t_df['Sum'][index]:  927.5118472774957
c[i]:  13354.454010634938
t_df['Sum'][index]:  936.0097984137828
c[i]:  14321.691830507561
t_df['Sum'][index]:  967.2378198726237
c[i]:  15323.449542345352
t_df['Sum'][index]:  1001.7577118377903
c[i]:  16326.574329062118
t_df['Sum'][index]:  1003.1247867167658
c[i]:  17342.31010007103
t_df['Sum'][index]:  1015.7357710089127
c[i]:  18378.461991695527
t_df['Sum'][index]:  1036.1518916244968
c[i]:  19415.564837583413
t_df['Sum'][index]:  1037.1028458878864
c[i]:  20464.380593405527
t_df['Sum'][index]:  1048.8157558221137
c[i]:  21523.088754953755
t_df['Sum'][index]:  1058.7081615482275
c[i]:  22585.441048402576
t_df['Sum'][index]:  1062.352293448822
c[i]:  23654.53083162956
t_df['Sum'][index]:  1069.0897832269839
c[i]:  24723.620614856547
t_df['Sum'][index]:  1069.0897832269857
c[i]:  25794.473375842434
t_df['Sum'][index]:  1070.8527609858866
c[i]:  26870.62526746693
t_df['Sum'][index]:  1076.1518916244968
c[i]:  27959.857143904625
t_df['Sum'][index]:  1089.2318764376942
c[i]:  29050.709904890507
t_df['Sum'][index]:  1090.8527609858832
c[i]:  30161.562665876387
t_df['Sum'][index]:  1110.8527609858793
c[i]:  31284.750475298028
t_df['Sum'][index]:  1123.1878094216408
c[i]:  32410.742509264903
t_df['Sum'][index]:  1125.9920339668752
c[i]:  33536.73454323178
t_df['Sum'][index]:  1125.9920339668752
c[i]:  34685.550299053895
t_df['Sum'][index]:  1148.8157558221155
c[i]:  35839.35467052495
t_df['Sum'][index]:  1153.8043714710511
c[i]:  36993.17982205014
t_df['Sum'][index]:  1153.825151525194
c[i]:  38164.44870365161
t_df['Sum'][index]:  1171.268881601467
c[i]:  39351.19503113833
t_df['Sum'][index]:  1186.746327486726
c[i]:  40538.480934799496
t_df['Sum'][index]:  1187.2859036611626
c[i]:  41787.67184428036
t_df['Sum'][index]:  1249.1909094808652
c[i]:  43057.917697686324
t_df['Sum'][index]:  1270.2458534059633
c[i]:  44337.71596913807
t_df['Sum'][index]:  1279.7982714517493
c[i]:  45703.85009631566
t_df['Sum'][index]:  1366.134127177589
c[i]:  47070.596423802395
t_df['Sum'][index]:  1366.7463274867314
c[i]:  48456.515252584584
t_df['Sum'][index]:  1385.918828782189
c[i]:  49870.319624055635
t_df['Sum'][index]:  1413.8043714710536
c[i]:  51357.46772820149
t_df['Sum'][index]:  1487.1481041458537
c[i]:  52897.57204929294
t_df['Sum'][index]:  1540.1043210914522

[48456.515252584584,
 27959.857143904625,
 22585.441048402576,
 0,
 30161.562665876387,
 33536.73454323178,
 21523.088754953755,
 41787.67184428036,
 1331.7584330628206,
 6055.029617924741,
 13354.454010634938,
 51357.46772820149,
 23654.53083162956,
 45703.85009631566,
 5204.176856938858,
 14321.691830507561,
 20464.380593405527,
 19415.564837583413,
 4397.751116670394,
 49870.319624055635,
 15323.449542345352,
 31284.750475298028,
 11490.93236494366,
 665.3326927943572,
 35839.35467052495,
 34685.550299053895,
 26870.62526746693,
 3610.2392693928987,
 32410.742509264903,
 10565.87369955417,
 2077.0911258571787,
 36993.17982205014,
 18378.461991695527,
 12418.444212221155,
 7808.563955757257,
 38164.44870365161,
 17342.31010007103,
 40538.480934799496,
 2841.634374641303,
 8717.168850508853,
 44337.71596913807,
 29050.709904890507,
 47070.596423802395,
 16326.574329062118,
 39351.19503113833,
 6929.355281829484,
 24723.620614856547,
 43057.917697686324,
 9640.914330154461,
 25794.473375842434]

Note: We will use sche_spt in question 3.

The waiting time matrix:

In [260]:
w

[0.0,
 665.3326927943572,
 1331.7584330628206,
 2077.0911258571787,
 2841.634374641303,
 3610.2392693928987,
 4397.751116670394,
 5204.176856938858,
 6055.029617924741,
 6929.355281829484,
 7808.563955757258,
 8717.168850508853,
 9640.914330154461,
 10565.87369955417,
 11490.93236494366,
 12418.444212221155,
 13354.454010634938,
 14321.691830507561,
 15323.449542345352,
 16326.574329062118,
 17342.31010007103,
 18378.461991695527,
 19415.564837583413,
 20464.380593405527,
 21523.088754953755,
 22585.441048402576,
 23654.530831629563,
 24723.620614856547,
 25794.473375842434,
 26870.62526746693,
 27959.857143904625,
 29050.709904890507,
 30161.562665876387,
 31284.750475298028,
 32410.742509264906,
 33536.73454323178,
 34685.550299053895,
 35839.35467052495,
 36993.17982205014,
 38164.44870365161,
 39351.19503113833,
 40538.480934799496,
 41787.67184428036,
 43057.917697686324,
 44337.71596913807,
 45703.85009631566,
 47070.596423802395,
 48456.515252584584,
 49870.319624055635,
 51357.46772820149]

The proof that c isn't dependent on the scheduling of the order:

In [261]:
max(c_spt)

52897.57204929294

The average waiting time for order:

In [262]:
sum(w)/J

23109.031093009165

### Question no. 3

First, we will calculate v and t for the new collector:

In [263]:
v2_df = v_df.copy()
v2_df = v2_df*1.15
v2_df

         veg       fru       oth
0   0.072560  0.076143  0.097458
1   0.111322  0.135235  0.100877
2   0.072560  0.166313  0.127778
3   0.166699  0.166313  0.212963
4   0.082339  0.097782  0.133721
5   0.072560  0.135235  0.117347
6   0.052962  0.483095  0.140244
7   0.072560  0.097782  0.108491
8   0.166699  0.166313  0.164286
9   0.111322  0.299275  0.122340
10  0.133942  0.135235  0.117347
11  0.044605  0.085676  0.112745
12  0.072560  0.166313  0.127778
13  0.082339  0.076143  0.097458
14  0.111322  0.135235  0.174242
15  0.082339  0.135235  0.147436
16  0.094840  0.085676  0.155405
17  0.072560  0.135235  0.147436
18  0.166699  0.214617  0.127778
19  0.058302  0.097782  0.088462
20  0.082339  0.214617  0.122340
21  0.058302  0.166313  0.140244
22  0.133942  0.166313  0.117347
23  0.166699  0.214617  0.185484
24  0.111322  0.085676  0.112745
25  0.072560  0.076143  0.174242
26  0.072560  0.113633  0.147436
27  0.133942  0.166313  0.164286
28  0.058302  0.166313  0.140244
29  0.166699  0.135235  0.117347
30  0.217884  0.135235  0.155405
31  0.111322  0.113633  0.094262
32  0.094840  0.214617  0.104545
33  0.094840  0.166313  0.140244
34  0.133942  0.214617  0.112745
35  0.082339  0.076143  0.140244
36  0.094840  0.113633  0.133721
37  0.058302  0.299275  0.094262
38  0.133942  0.214617  0.155405
39  0.064718  0.483095  0.155405
40  0.058302  0.113633  0.100877
41  0.111322  0.135235  0.097458
42  0.048456  0.135235  0.108491
43  0.094840  0.135235  0.127778
44  0.048456  0.214617  0.140244
45  0.094840  0.299275  0.133721
46  0.111322  0.135235  0.104545
47  0.064718  0.085676  0.127778
48  0.217884  0.113633  0.117347
49  0.094840  0.113633  0.122340

In [264]:
t2 = {"veg":[],"fru":[], "oth":[]}
for i in t2.keys():
    for j in range(J):
        if i == "veg" or i == "fru":
            t2[i].append(len_shelf/v2_df[i][j])
        else:
            t2[i].append(len_pass/v2_df[i][j])
t2_df = pd.DataFrame(t2)
t2_df['Sum'] = t2_df.sum(axis=1)
t2_df

           veg         fru         oth          Sum
0   344.541998  328.331368  513.043478  1185.916845
1   224.574177  184.863007  495.652174   905.089357
2   344.541998  150.318683  391.304348   886.165029
3   149.970615  150.318683  234.782609   535.071907
4   303.621960  255.671787  373.913043   933.206791
5   344.541998  184.863007  426.086957   955.491962
6   472.034989   51.749614  356.521739   880.306342
7   344.541998  255.671787  460.869565  1061.083351
8   149.970615  150.318683  304.347826   604.637124
9   224.574177   83.535096  408.695652   716.804925
10  186.648141  184.863007  426.086957   797.598104
11  560.469107  291.795520  443.478261  1295.742888
12  344.541998  150.318683  391.304348   886.165029
13  303.621960  328.331368  513.043478  1144.996807
14  224.574177  184.863007  286.956522   696.393705
15  303.621960  184.863007  339.130435   827.615402
16  263.602881  291.795520  321.739130   877.137532
17  344.541998  184.863007  339.130435   868.535440
18  149.970615  116.486550  391.304348   657.761513
19  428.804825  255.671787  565.217391  1249.694004
20  303.621960  116.486550  408.695652   828.804162
21  428.804825  150.318683  356.521739   935.645247
22  186.648141  150.318683  426.086957   763.053780
23  149.970615  116.486550  269.565217   536.022383
24  224.574177  291.795520  443.478261   959.847958
25  344.541998  328.331368  286.956522   959.829888
26  344.541998  220.007459  339.130435   903.679893
27  186.648141  150.318683  304.347826   641.314650
28  428.804825  150.318683  356.521739   935.645247
29  149.970615  184.863007  426.086957   760.920579
30  114.739818  184.863007  321.739130   621.341955
31  224.574177  220.007459  530.434783   975.016419
32  263.602881  116.486550  478.260870   858.350301
33  263.602881  150.318683  356.521739   770.443303
34  186.648141  116.486550  443.478261   746.612952
35  303.621960  328.331368  356.521739   988.475067
36  263.602881  220.007459  373.913043   857.523384
37  428.804825   83.535096  530.434783  1042.774704
38  186.648141  116.486550  321.739130   624.873822
39  386.289933   51.749614  321.739130   759.778678
40  428.804825  220.007459  495.652174  1144.464458
41  224.574177  184.863007  513.043478   922.480662
42  515.935975  184.863007  460.869565  1161.668547
43  263.602881  184.863007  391.304348   839.770236
44  515.935975  116.486550  356.521739   988.944264
45  263.602881   83.535096  373.913043   721.051021
46  224.574177  184.863007  478.260870   887.698053
47  386.289933  291.795520  391.304348  1069.389801
48  114.739818  220.007459  426.086957   760.834234
49  263.602881  220.007459  408.695652   892.305993

In [265]:
internal_arrangement(t2_df, len_pass = len_pass/1.15)
spt_algo(t2_df)
t2_df

c[i]:  578.5501676472677
t_df['Sum'][index]:  578.5501676472677
c[i]:  1158.0508113589722
t_df['Sum'][index]:  579.5006437117045
c[i]:  1806.166196397543
t_df['Sum'][index]:  648.1153850385708
c[i]:  2470.9864127315677
t_df['Sum'][index]:  664.8202163340247
c[i]:  3139.338495124256
t_df['Sum'][index]:  668.3520823926883
c[i]:  3824.1314058003345
t_df['Sum'][index]:  684.7929106760785
c[i]:  4525.371179946823
t_df['Sum'][index]:  701.2397741464883
c[i]:  5265.243146021504
t_df['Sum'][index]:  739.871966074681
c[i]:  6025.526332025628
t_df['Sum'][index]:  760.2831860041242
c[i]:  6790.055613701953
t_df['Sum'][index]:  764.5292816763249
c[i]:  7580.146826529429
t_df['Sum'][index]:  790.0912128274758
c[i]:  8383.40376535169
t_df['Sum'][index]:  803.2569388222619
c[i]:  9187.71626048187
t_df['Sum'][index]:  804.3124951301797
c[i]:  9992.115099950992
t_df['Sum'][index]:  804.3988394691223
c[i]:  10798.647141061854
t_df['Sum'][index]:  806.5320411108623
c[i]:  11612.568704899928
t_df['Sum'][index]:  813.9215638380738
c[i]:  12453.645070006558
t_df['Sum'][index]:  841.07636510663
c[i]:  13324.738732474203
t_df['Sum'][index]:  871.0936624676451
c[i]:  14197.021155706176
t_df['Sum'][index]:  872.2824232319726
c[i]:  15080.269652235676
t_df['Sum'][index]:  883.2484965295007
c[i]:  15981.271297126548
t_df['Sum'][index]:  901.0016448908718
c[i]:  16883.09985876819
t_df['Sum'][index]:  901.8285616416433
c[i]:  17795.11355948307
t_df['Sum'][index]:  912.0137007148824
c[i]:  18715.729352133705
t_df['Sum'][index]:  920.615792650633
c[i]:  19639.51395513268
t_df['Sum'][index]:  923.784602998976
c[i]:  20569.157244895272
t_df['Sum'][index]:  929.6432897625946
c[i]:  21498.80053465787
t_df['Sum'][index]:  929.6432897625955
c[i]:  22429.976848558636
t_df['Sum'][index]:  931.1763139007671
c[i]:  23365.761102145163
t_df['Sum'][index]:  935.7842535865275
c[i]:  24312.919255569243
t_df['Sum'][index]:  947.1581534240795
c[i]:  25261.486873817837
t_df['Sum'][index]:  948.5676182485943
c[i]:  26227.445796414253
t_df['Sum'][index]:  965.9589225964155
c[i]:  27204.130848085246
t_df['Sum'][index]:  976.6850516709919
c[i]:  28183.254355882527
t_df['Sum'][index]:  979.1235077972815
c[i]:  29162.37786367981
t_df['Sum'][index]:  979.1235077972815
c[i]:  30161.34808613382
t_df['Sum'][index]:  998.9702224540133
c[i]:  31164.656235239083
t_df['Sum'][index]:  1003.3081491052617
c[i]:  32167.982453956643
t_df['Sum'][index]:  1003.3262187175606
c[i]:  33186.47713361009
t_df['Sum'][index]:  1018.4946796534459
c[i]:  34218.43046185942
t_df['Sum'][index]:  1031.9533282493321
c[i]:  35250.85298678216
t_df['Sum'][index]:  1032.4225249227457
c[i]:  36337.10595154813
t_df['Sum'][index]:  1086.2529647659685
c[i]:  37441.66756320549
t_df['Sum'][index]:  1104.5616116573592
c[i]:  38554.53562533745
t_df['Sum'][index]:  1112.8680621319581
c[i]:  39742.47834462231
t_df['Sum'][index]:  1187.9427192848598
c[i]:  40930.953412002076
t_df['Sum'][index]:  1188.4750673797662
c[i]:  42136.10021963876
t_df['Sum'][index]:  1205.1468076366873
c[i]:  43365.495325265765
t_df['Sum'][index]:  1229.3951056270032
c[i]:  44658.66758974042
t_df['Sum'][index]:  1293.172264474655
c[i]:  45997.8887385156
t_df['Sum'][index]:  1339.2211487751756

           veg         fru         oth          Sum
0   344.541998  328.331368  513.043478  1229.395106
1   224.574177  184.863007  495.652174   948.567618
2   344.541998  150.318683  391.304348   929.643290
3   149.970615  150.318683  234.782609   578.550168
4   303.621960  255.671787  373.913043   976.685052
5   344.541998  184.863007  426.086957   998.970222
6   472.034989   51.749614  356.521739   923.784603
7   344.541998  255.671787  460.869565  1104.561612
8   149.970615  150.318683  304.347826   648.115385
9   224.574177   83.535096  408.695652   760.283186
10  186.648141  184.863007  426.086957   841.076365
11  560.469107  291.795520  443.478261  1339.221149
12  344.541998  150.318683  391.304348   929.643290
13  303.621960  328.331368  513.043478  1188.475067
14  224.574177  184.863007  286.956522   739.871966
15  303.621960  184.863007  339.130435   871.093662
16  263.602881  291.795520  321.739130   920.615793
17  344.541998  184.863007  339.130435   912.013701
18  149.970615  116.486550  391.304348   701.239774
19  428.804825  255.671787  565.217391  1293.172264
20  303.621960  116.486550  408.695652   872.282423
21  428.804825  150.318683  356.521739   979.123508
22  186.648141  150.318683  426.086957   806.532041
23  149.970615  116.486550  269.565217   579.500644
24  224.574177  291.795520  443.478261  1003.326219
25  344.541998  328.331368  286.956522  1003.308149
26  344.541998  220.007459  339.130435   947.158153
27  186.648141  150.318683  304.347826   684.792911
28  428.804825  150.318683  356.521739   979.123508
29  149.970615  184.863007  426.086957   804.398839
30  114.739818  184.863007  321.739130   664.820216
31  224.574177  220.007459  530.434783  1018.494680
32  263.602881  116.486550  478.260870   901.828562
33  263.602881  150.318683  356.521739   813.921564
34  186.648141  116.486550  443.478261   790.091213
35  303.621960  328.331368  356.521739  1031.953328
36  263.602881  220.007459  373.913043   901.001645
37  428.804825   83.535096  530.434783  1086.252965
38  186.648141  116.486550  321.739130   668.352082
39  386.289933   51.749614  321.739130   803.256939
40  428.804825  220.007459  495.652174  1187.942719
41  224.574177  184.863007  513.043478   965.958923
42  515.935975  184.863007  460.869565  1205.146808
43  263.602881  184.863007  391.304348   883.248497
44  515.935975  116.486550  356.521739  1032.422525
45  263.602881   83.535096  373.913043   764.529282
46  224.574177  184.863007  478.260870   931.176314
47  386.289933  291.795520  391.304348  1112.868062
48  114.739818  220.007459  426.086957   804.312495
49  263.602881  220.007459  408.695652   935.784254

prep for Q//c_max - for more info go to doc:

calc the ratio of the task index (K) to the working rate of the gatherer (s_j: s1 = 1, s2 = 1.15): K/s_j

In [266]:
K_S1 = [i for i in range(1, J+1)]

K_S2 = [0 for i in range(1, J+1)]
for i in range(1, 51):
    K_S2[i-1] = i/1.15

As we do in Q//sigma(C_i): take the task with the longest time and match it to the min ratio of both gatherers.

* The heuristics will be to place the tasks from the beginning and not the end (as we do in P//c_max). 

* Note the longest task will be the same for the both gatherers since the ratio is permanent

In [267]:
#initializing schedules: 1 for the regular, 2 for the faster one
sch_1_Q3 = []
sch_2_Q3 = []

#initializing time counters
time_1 = 0
time_2 = 0

# to compare with Q4 - initializing dictionaries for waiting time to each task in specific gather. 
waiting_time_1 = {}
waiting_time_2 = {}

#copy for processing times
t_df_copy = t_df.copy()


for i in range(J):
    task_idx = t_df_copy['Sum'].idxmax() # task index with max time
    task_time_1 = t_df_copy['Sum'][task_idx] # time processing for the regular
    task_time_2 = t2_df['Sum'][task_idx] ## time processing for the fast gather

    t_df_copy['Sum'][task_idx] = None # for not using it again
    
    # taking min ratio
    min_K_S1 = min(K_S1)
    min_K_S2 = min(K_S2)
    
    min_tot = 0
    
    #case the min ratio is for the regular gather
    if min_K_S1 < min_K_S2:
        waiting_time_1[task_idx] = time_1 # waiting time until now, not including the process time for this task
        min_tot = min_K_S1
        idx = K_S1.index(min_tot)
        K_S1.pop(idx)
            
        sch_1_Q3.append(task_idx) # add the task to regular gather schedule
            
        time_1 += task_time_1 # update time
    
    #case the min ratio is for the fast gather    
    else:
        waiting_time_2[task_idx] = time_2 # waiting time until now, not including the process time for this task
        min_tot = min_K_S2
        idx = K_S2.index(min_tot)
        K_S2.pop(idx)
            
        sch_2_Q3.append(task_idx) # add the task to faster gather schedule
            
        time_2 += task_time_2 # update time


time_finish = max(time_2, time_1) # C_MAX

print('time_finish: ',time_finish)
print('sch for regular gather: ', sch_1_Q3)
print('sch for fast gather: ', sch_2_Q3)

time_finish:  24799.220009205586
sch for regular gather:  [19, 42, 40, 7, 44, 31, 5, 28, 41, 26, 46, 2, 16, 36, 20, 10, 22, 48, 34, 14, 27, 30, 23]
sch for fast gather:  [11, 0, 13, 47, 37, 35, 24, 25, 21, 4, 1, 49, 12, 6, 17, 32, 43, 15, 33, 29, 39, 45, 9, 18, 38, 8, 3]

In [268]:
#to compare woth Q4
total_wt_1 = sum(list(waiting_time_1.values()))
avg_wt_1 = total_wt_1/len(list(waiting_time_1.values()))

total_wt_2 = sum(list(waiting_time_2.values()))
avg_wt_2 = total_wt_2/len(list(waiting_time_2.values()))

total_wt_both = total_wt_1 + total_wt_2
avg_wt__both = total_wt_both/J

### Question no. 4

re-calc the ratio of the task index (K) to the working rate of the gatherer (s_j: s1 = 1, s2 = 1.15): K/s_j

In [269]:
#prep for the ratios 
K_S1_Q4 = [i for i in range(1, J+1)]

K_S2_Q4 = [0 for i in range(1, J+1)]
for i in range(1, 51):
    K_S2_Q4[i-1] = i/1.15

As we do in Q//sigma(C_i): take the task with the longest time and match it to the min ratio of both gatherers. 

* Will place the tasks from end to beginning as should do in Q//sigma(C_i). 

* Note the longest task will be the same for the both gatherers since the ratio is permanent

In [270]:
#initializing schedules: 1 for the regular, 2 for the faster one
sch_1_Q4 = []
sch_2_Q4 = []

#initializing time counters
time_1_Q4 = 0
time_2_Q4 = 0

# initializing dictionaries for waiting time to each task in specific gather. 
waiting_time_1_Q4 = {}
waiting_time_2_Q4 = {}

#copy for processing times
t_Q4_copy = t_df.copy()

### same algo as Q3 - no time clculations
for i in range(J):
    task_idx = t_Q4_copy['Sum'].idxmax() # task index with max time
    task_time_1 = t_Q4_copy['Sum'][task_idx] # time processing for the regular
    task_time_2 = t2_df['Sum'][task_idx] ## time processing for the fast gather
    
    t_Q4_copy['Sum'][task_idx] = None # for not using it again
    
    # taking min ratio
    min_K_S1 = min(K_S1_Q4)
    min_K_S2 = min(K_S2_Q4)
    
    min_tot = 0
    
    #case the min ratio is for the regular gather
    if min_K_S1 < min_K_S2:
        min_tot = min_K_S1
        idx = K_S1_Q4.index(min_tot)
        K_S1_Q4.pop(idx)
            
        sch_1_Q4.append([task_idx, task_time_1]) # add the task to regular gather schedule
    
    #case the min ratio is for the fast gather    
    else:
        min_tot = min_K_S2
        idx = K_S2_Q4.index(min_tot)
        K_S2_Q4.pop(idx)
            
        sch_2_Q4.append([task_idx,task_time_2]) # add the task to faster gather schedule
###

### New - Assign tasks from end to beginning
t1=0 # time (regular gather) counter
agg_time_1 = [0] # Auxiliary variable in order to calculate waiting time 
sch_1_rev = [] # Auxiliary variable to reverse scheduale
sch_1_final = []

for i in range(len(sch_1_Q4)):
    sch_1_rev.append(sch_1_Q4[-1])
    t1 += sch_1_Q4[-1][1]  # accumulation
    sch_1_Q4.pop(-1)
    
    agg_time_1.append(t1) # list of waiting time - no task index
    
    waiting_time_1_Q4[sch_1_rev[i][0]] = agg_time_1[i] # dict of waiting time- k= task, v= waiting time (reg gather)
    
    sch_1_final.append(sch_1_rev[i][0])


t2=0 # time (fast gather) counter
agg_time_2 = [0] # Auxiliary variable in order to calculate waiting time
sch_2_rev = [] # Auxiliary variable to reverse scheduale
sch_2_final = []

for i in range(len(sch_2_Q4)):
    sch_2_rev.append(sch_2_Q4[-1]) 
    t2 += sch_2_Q4[-1][1] # accumulation
    sch_2_Q4.pop(-1)
    
    agg_time_2.append(t2) # list of waiting time - no task index
    
    waiting_time_2_Q4[sch_2_rev[i][0]] = agg_time_2[i] # dict of waiting time- k= task, v= waiting time (fast gather)
    
    sch_2_final.append(sch_2_rev[i][0])


time_finish_Q4 = max(agg_time_1[-1], agg_time_2[-1]) # C_MAX

print('time_finish Q4: ', time_finish_Q4)
print('sch for regular gather: ', sch_1_final)
print('sch for fast gather: ', sch_2_final)

time_finish Q4:  24799.220009205586
sch for regular gather:  [23, 30, 27, 14, 34, 48, 22, 10, 20, 36, 16, 2, 46, 26, 41, 28, 5, 31, 44, 7, 40, 42, 19]
sch for fast gather:  [3, 8, 38, 18, 9, 45, 39, 29, 33, 15, 43, 32, 17, 6, 12, 49, 1, 4, 21, 25, 24, 35, 37, 47, 13, 0, 11]

As we expected all schedules are reversed (Q3 vs Q4). 

Now will compare waiting time:

In [271]:
#print('waiting_time for 1: ', waiting_time_1_Q4.items())
total_wt_1_Q4 = sum(list(waiting_time_1_Q4.values()))
avg_wt_1_Q4 = total_wt_1_Q4/len(list(waiting_time_1_Q4.values()))
print('Regular worker:')
print('-----------------------------------------------------')
print('The total waiting time in Q3: ',total_wt_1, 'and the avg waiting time: ',avg_wt_1)
print('Total waiting time Q4: ',total_wt_1_Q4, ' and avg waiting time Q4: ', avg_wt_1_Q4)

print('-----------------------------------------------------')
print('-----------------------------------------------------')


total_wt_2_Q4 = sum(list(waiting_time_2_Q4.values()))
avg_wt_2_Q4 = total_wt_2_Q4/len(list(waiting_time_2_Q4.values()))
print('Fast worker:')
print('-----------------------------------------------------')
print('The total waiting time in Q3: ',total_wt_2, 'and the avg waiting time in Q3: ',avg_wt_2)
print('Total waiting time Q4: ', total_wt_2_Q4,'and avg waiting tine Q4: ',avg_wt_2_Q4)

print('-----------------------------------------------------')
print('-----------------------------------------------------')

total_wt_both_Q4 = total_wt_1_Q4 + total_wt_2_Q4
avg_wt__both_Q4 = total_wt_both_Q4/J
print('Both workers:')
print('-----------------------------------------------------')
print('The total waiting time in Q3: ',total_wt_both,' and The avg waiting time in Q3: ',avg_wt__both)
print('Total waiting time Q4: ', total_wt_both_Q4, ' and avg waiting time Q4: ',avg_wt__both_Q4)

Regular worker:
-----------------------------------------------------
The total waiting time in Q3:  297579.25551341433 and the avg waiting time:  12938.228500583233
Total waiting time Q4:  238747.06333812946  and avg waiting time Q4:  10380.307101657803
-----------------------------------------------------
-----------------------------------------------------
Fast worker:
-----------------------------------------------------
The total waiting time in Q3:  358288.51004933787 and the avg waiting time in Q3:  13269.944816642143
Total waiting time Q4:  286491.21019000723 and avg waiting tine Q4:  10610.78556259286
-----------------------------------------------------
-----------------------------------------------------
Both workers:
-----------------------------------------------------
The total waiting time in Q3:  655867.7655627523  and The avg waiting time in Q3:  13117.355311255045
Total waiting time Q4:  525238.2735281367  and avg waiting time Q4:  10504.765470562734

### Question no. 5

Redefinig the time metrix that takes to do each type of order for each worker, by using velpcity matrix:

In [272]:
t5 = {"veg":[],"fru":[], "oth":[]} # A dataframe of collector's times
for i in t5.keys(): # For each type of order
    for j in range(J): # For each order
        if i == "veg" or i == "fru": # Because veggies and fruits are in the same passage
            t5[i].append(len_shelf/v2_df[i][j]) # only for worker 2 - the fast worker
        else: # Because others are in different passege
            t5[i].append(len_pass/v_df[i][j]) # only for worker 1 - the regular worker
t5_df = pd.DataFrame(t)
t5_df['Sum'] = t5_df["veg"] + t5_df["fru"] # only for worker 2 - the fast worker 
t5_df

           veg         fru    oth         Sum
0   396.223298  377.581073  590.0  773.804371
1   258.260303  212.592458  570.0  470.852761
2   396.223298  172.866485  450.0  569.089783
3   172.466208  172.866485  270.0  345.332693
4   349.165254  294.022555  430.0  643.187809
5   396.223298  212.592458  490.0  608.815756
6   542.840237   59.512056  410.0  602.352293
7   396.223298  294.022555  530.0  690.245853
8   172.466208  172.866485  350.0  345.332693
9   258.260303   96.065361  470.0  354.325664
10  214.645362  212.592458  490.0  427.237820
11  644.539473  335.564848  510.0  980.104321
12  396.223298  172.866485  450.0  569.089783
13  349.165254  377.581073  590.0  726.746327
14  258.260303  212.592458  330.0  470.852761
15  349.165254  212.592458  390.0  561.757712
16  303.143313  335.564848  370.0  638.708162
17  396.223298  212.592458  390.0  608.815756
18  172.466208  133.959533  450.0  306.425740
19  493.125549  294.022555  650.0  787.148104
20  349.165254  133.959533  470.0  483.124787
21  493.125549  172.866485  410.0  665.992034
22  214.645362  172.866485  490.0  387.511847
23  172.466208  133.959533  310.0  306.425740
24  258.260303  335.564848  510.0  593.825152
25  396.223298  377.581073  330.0  773.804371
26  396.223298  253.008578  390.0  649.231876
27  214.645362  172.866485  350.0  387.511847
28  493.125549  172.866485  410.0  665.992034
29  172.466208  212.592458  490.0  385.058665
30  131.950791  212.592458  370.0  344.543249
31  258.260303  253.008578  610.0  511.268882
32  303.143313  133.959533  550.0  437.102846
33  303.143313  172.866485  410.0  476.009798
34  214.645362  133.959533  510.0  348.604895
35  349.165254  377.581073  410.0  726.746327
36  303.143313  253.008578  430.0  556.151892
37  493.125549   96.065361  610.0  589.190909
38  214.645362  133.959533  370.0  348.604895
39  444.233423   59.512056  370.0  503.745480
40  493.125549  253.008578  570.0  746.134127
41  258.260303  212.592458  590.0  470.852761
42  593.326371  212.592458  530.0  805.918829
43  303.143313  212.592458  450.0  515.735771
44  593.326371  133.959533  410.0  727.285904
45  303.143313   96.065361  430.0  399.208674
46  258.260303  212.592458  550.0  470.852761
47  444.233423  335.564848  450.0  779.798271
48  131.950791  253.008578  490.0  384.959369
49  303.143313  253.008578  470.0  556.151892

Depends on the assumptions and the work division between the workers -  C_max cannot be minimized. We make sure that each worker handles an order only if necessary, and calculate the finish time accordingly.

In [273]:
#initializing schedules: 1 for the regular, 2 for the faster one
sch_1_Q5 = {i : None for i in range(50)}
sch_2_Q5 = {i : None for i in range(50)}

def internal_arrangement_Q5(t_df):
    # Defining clock of the simulation
    t1_now = 0
    t2_now = 0 
    c1 = [0 for i in range(J)] # Definig end time matrix - for worker 1
    c2 = [0 for i in range(J)] # Definig end time matrix - for worker 2
    c_total = [0 for i in range(J)] # Definig end time matrix - for each order - Max(c1_j,c2_j)
    schedule1 = [0 for i in range(J)] # Defining the schedule for each order - for worker 1 (the start times)
    schedule2 = [0 for i in range(J)] # Defining the schedule for each order - for worker 2 (the start times)
    w_total = [0 for i in range(J)] # Defining  waiting time for each order

    for i in range(J): # For each order 
        if m_df[1][i] > 0 or m_df[2][i] > 0: # If there are fruits or veggies to collect - for worker 2
            schedule1[i] += t1_now # Schedule the order for now
            t1_now += t5_df["Sum"][i]
            c1[i] = t1_now # Defining the end time of the order after all the collections
            sch_2_Q5[i]= i
        if m_df[3][i] > 0: # if there are others to collect - for worker 1
            schedule2[i] += t2_now # Schedule the order for now
            t2_now += t5_df["oth"][i]
            c2[i] = t2_now # Defining the end time of the order after all the collections
            sch_1_Q5[i]= i


    for i in range(J):
        c_total[i] = max(c1[i], c2[i])
        if ((schedule1[i] <= c2[i]) and (c1[i] >= schedule2[i])) or ((schedule2[i] <= c1[i]) and (c2[i] >= schedule1[i])):
            w_total[i] = min(schedule1[i], schedule2[i])
        else:
            processing_time = t5_df["oth"][i] + t5_df["Sum"][i]
            w_total[i] = c_total[i] - processing_time
    
    c_max_Q5 = max(c_total)

    return c1, c2, schedule1, schedule2, sch_1_Q5, sch_2_Q5, c_max_Q5, w_total
 
c1, c2, schedule1, schedule2, sch_1_Q5, sch_2_Q5, c_max_Q5, w_total_Q5 = internal_arrangement_Q5(t5_df)

### Question no. 6

In [274]:
# Setting exclusive orders for each worker
only_worker1 = {} # Only worker 1 is responsible for the order - only "oth" 
only_worker2 = {} # Only worker 2 is responsible for the order - "veg", "fru"

for i in range(J): # For each order:
    if m_df[1][j] == 0 and m_df[2][j] == 0 and m_df[3][j] > 0: # If there are only "oth" in the order
        only_worker1[j] = t5_df["oth"][j]
    if (m_df[1][j] > 0 or m_df[2][j] > 0) and m_df[3][j] == 0: # If there are not "oth" in the order
        only_worker1[j] = t5_df["Sum"][j]
# Sort the orders from the shortest to the longest - for spt algo    
dict(sorted(only_worker1.items(), key=lambda item: item[1]))
dict(sorted(only_worker2.items(), key=lambda item: item[1]))

#initializing schedules: 1 for the regular, 2 for the faster one
sch_1_Q6 = {i : None for i in range(50)}
sch_2_Q6 = {i : None for i in range(50)}

def get_key(dic, val):
    for key, value in dic.items():
         if val == value:
             return key

def spt_algo_Q6(t_df):
    
    t1_now = 0 # Start Time of worker 1
    t2_now = 0 # Start Time of worker 1 
    t_oth_copy = t5_df["oth"].copy() # Creating a copy of  'Sum' column - for worker 1
    t_sum_copy = t5_df["Sum"].copy() # Creating a copy of 'oth' column - for worker 2
    c1 = [0 for i in range(J)] # Definig end time matrix - for worker 1
    c2 = [0 for i in range(J)] # Definig end time matrix - for worker 2
    c_total = [0 for i in range(J)] # Definig end time matrix - for each order - Max(c1_j,c2_j)
    schedule1 = [0 for i in range(J)] # Defining the schedule for each order - for worker 1 (the start times)
    schedule2 = [0 for i in range(J)] # Defining the schedule for each order - for worker 2 (the start times)
    w_total = [0 for i in range(J)] # Defining  waiting time for each order

    for i in range(J): # For each order
        index = t_oth_copy.idxmin() # Pull the id of the minimal processing time - for worker 1 
        schedule1[index] += t1_now # Scheduling the shortest order for current time
        t1_now += t_oth_copy[index] # Moving the sim clock to the end of the order
        c1[index] = t1_now 
        t_oth_copy[index] = None # "Deleting" the minimal processing time, so we can find the next minimal time
        sch_1_Q6[i]= index

        # If the order is also relevant for the worker 2
        if not i in only_worker1: 
            sch_2_Q6[i] = index

    for i in range (len(only_worker2)): # For each exclusive order of worker 2
        if only_worker1: # If there is an exclusive task of worker 1
            curr_key, curr_val = list(only_worker1.items())[0] # Worker1's shortest order
            only_worker1.pop(curr_key) # Pop the minimal processing time, so we can find the next minimal time
            rel_key = get_key(sch_1_Q6, curr_val) # Get the serial number of the current order by the schedule of worker 1
        else:
            rel_key = get_key(sch_2_Q6, None) # Get a serial number of "free time slot" of worker 2
        sch_2_Q6[rel_key] = list(only_worker2.keys())[i] # Insert the exclusive order of worker 2

    # Calculating times of worker 2
    for i in range(J):
        index = sch_2_Q6[i] # The shortest current order of worker 2 (sorted dictionary by keys)
        schedule2[index] += t2_now # Scheduling the shortest order for current time
        t2_now += t_sum_copy[index] # Moving the sim clock to the end of the order
        c2[index] = t2_now # Definig the end time of the order
    
    # Calculation of waiting times
    for i in range(J):
        c_total[i] = max(c1[i], c2[i])
        if ((schedule1[i] <= c2[i]) and (c1[i] >= schedule2[i])) or ((schedule2[i] <= c1[i]) and (c2[i] >= schedule1[i])):
            w_total[i] = min(schedule1[i], schedule2[i])
        else:
            processing_time = t5_df["oth"][i] + t5_df["Sum"][i]
            w_total[i] = c_total[i] - processing_time
    
    c_max_Q6 = max(c_total)

    return sch_1_Q6, schedule1, c1,  sch_2_Q6, schedule2, c2, c_max_Q6, w_total 
    
sch_1_Q6, schedule1_Q6, c1, sch_2_Q6, schedule2_Q6, c2_Q6, c_max_Q6, w_total_Q6 = spt_algo_Q6(t5_df)

In [275]:
sum_w_total_Q5 = sum(w_total_Q5)
avg_w_total_Q5 = sum_w_total_Q5/J

sum_w_total_Q6 = sum(w_total_Q6)
avg_w_total_Q6 = sum_w_total_Q6/J

schedule1_lst_Q5 = list(sch_1_Q5.values())
schedule2_lst_Q5 = list(sch_2_Q5.values())

schedule1_lst_Q6 = list(sch_1_Q6.values())
schedule2_lst_Q6 = list(sch_1_Q6.values()) 

print ("Q_5")
print('The total waiting time in Q5: ',sum_w_total_Q5,' and the avg waiting time in Q5: ',avg_w_total_Q5)
print('C_max in Q5: ',c_max_Q5)
print ('Schedule of worker 1:')
print (schedule1_lst_Q5)
print ('Schedule of worker 2:')
print (schedule2_lst_Q5)

print ("\n")

print ("Q_6")
print('The total waiting time in Q6: ',sum_w_total_Q6,' and the avg waiting time in Q6: ',avg_w_total_Q6)
print('C_max in Q6: ',c_max_Q6)
print ('Schedule of worker 1:')
print (schedule1_lst_Q6)
print ('Schedule of worker 2:')
print (schedule2_lst_Q6)

Q_5
The total waiting time in Q5:  657951.2562377579  and the avg waiting time in Q5:  13159.025124755157
C_max in Q5:  27477.572049292932
Schedule of worker 1:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
Schedule of worker 2:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]


Q_6
The total waiting time in Q6:  622628.9176307233  and the avg waiting time in Q6:  12452.578352614466
C_max in Q6:  27477.57204929294
Schedule of worker 1:
[3, 23, 14, 25, 8, 27, 16, 30, 38, 39, 15, 17, 26, 6, 21, 28, 33, 35, 44, 4, 36, 45, 2, 12, 18, 43, 47, 9, 20, 49, 5, 10, 22, 29, 48, 11, 24, 34, 7, 42, 32, 46, 1, 40, 0, 13, 41, 31, 37, 19]
Schedule of worker 2:
[3, 23, 14, 25, 8, 27, 16, 30, 38, 39, 15, 17, 26, 6, 21, 28, 33, 35, 44, 4, 36, 45, 2, 12, 18, 43, 47, 9, 20, 49, 5, 10, 22, 29, 48, 11, 24, 34, 7, 42, 32, 46, 1, 40, 0, 13, 41, 31, 37, 19]