## Production Systems Analysis Project
Owners: Almog Asraf, Daniel Pidtylok, Nir Levanon, Shani Yorav

### Imports

In [51]:
import numpy as np
import pandas as pd

### Parameters

In [52]:
J = 50 # Numbers of the orders

Creating the amount of vegtables, fruits and others from poission destribution:

In [53]:
lamb = [7.5, 5.2, 20] # Lambdas for the poission destribution
m = {1:[],2:[],3:[]} # 1: veggies, 2: fruits, 3: other
for i in m.keys(): # For each type of order
    for j in range(J): # For each order
        m[i].append(np.random.poisson(lamb[i-1]))
m_df = pd.DataFrame(m) # More easy to work with pandas df
m_df

     1  2   3
0    5  6  18
1    8  2  18
2    3  5  19
3    5  4  18
4    7  6  16
5    6  6  19
6   11  2  20
7    9  3  20
8   10  9  15
9    7  9  17
10   7  1  21
11   7  8  12
12   7  2  17
13   7  9  23
14  12  4  38
15   7  4  18
16   7  7  14
17   6  5  17
18   6  1  20
19   9  4  17
20  14  4  20
21   9  8  20
22   6  5  19
23   9  6  14
24   8  2  24
25   5  6  22
26   6  3  24
27  11  4  21
28   7  7  14
29   2  9  21
30   7  5  26
31   3  4  15
32  12  2  22
33   7  4  20
34   5  6  10
35   7  3  17
36   7  4  16
37   9  7  20
38   5  5  21
39   9  5  21
40   8  3  20
41   9  4  32
42   8  4  11
43   8  7  20
44   7  5  22
45   9  7  21
46   7  9  24
47   6  4  21
48   7  4  28
49   6  5  16

Creating the velocity matrix for each order:

In [54]:
v = {"veg":[],"fru":[], "oth":[]} # A dataframe of collector's velocity
for i in v.keys(): # For each type of order
    for j in range(J): # For each order
        if i == "veg":
            v[i].append((25/(25+25*m[1][j]))**1.2)
        elif i == "fru":
            v[i].append((25/(25+30*m[2][j]))**1.1)
        else:
            v[i].append(25/(25+10*m[3][j]))
v_df = pd.DataFrame(v) # More easy to work with pandas
v_df

         veg       fru       oth
0   0.116471  0.098811  0.121951
1   0.071599  0.260239  0.121951
2   0.189465  0.117596  0.116279
3   0.116471  0.144620  0.121951
4   0.082469  0.098811  0.135135
5   0.096802  0.098811  0.116279
6   0.050697  0.260239  0.111111
7   0.063096  0.186624  0.111111
8   0.056277  0.066211  0.142857
9   0.082469  0.066211  0.128205
10  0.082469  0.420083  0.106383
11  0.082469  0.074501  0.172414
12  0.082469  0.260239  0.128205
13  0.082469  0.066211  0.098039
14  0.046054  0.144620  0.061728
15  0.082469  0.144620  0.121951
16  0.082469  0.085027  0.151515
17  0.096802  0.117596  0.128205
18  0.096802  0.420083  0.111111
19  0.063096  0.144620  0.128205
20  0.038787  0.144620  0.111111
21  0.063096  0.074501  0.111111
22  0.096802  0.117596  0.116279
23  0.063096  0.098811  0.151515
24  0.071599  0.260239  0.094340
25  0.116471  0.098811  0.102041
26  0.096802  0.186624  0.094340
27  0.050697  0.144620  0.106383
28  0.082469  0.085027  0.151515
29  0.267581  0.066211  0.106383
30  0.082469  0.117596  0.087719
31  0.189465  0.144620  0.142857
32  0.046054  0.260239  0.102041
33  0.082469  0.144620  0.111111
34  0.116471  0.098811  0.200000
35  0.082469  0.186624  0.128205
36  0.082469  0.144620  0.135135
37  0.063096  0.085027  0.111111
38  0.116471  0.117596  0.106383
39  0.063096  0.117596  0.106383
40  0.071599  0.186624  0.111111
41  0.063096  0.144620  0.072464
42  0.071599  0.144620  0.185185
43  0.071599  0.085027  0.111111
44  0.082469  0.117596  0.102041
45  0.063096  0.085027  0.106383
46  0.082469  0.066211  0.094340
47  0.096802  0.144620  0.106383
48  0.082469  0.144620  0.081967
49  0.096802  0.117596  0.135135

Definig the length of each shelf:

In [55]:
len_shelf = 25
len_pass = len_shelf*2

Definig the time metrix that takes to do each type of order, by using velpcity matrix:

In [56]:
t = {"veg":[],"fru":[], "oth":[]} # A dataframe of collector's times
for i in t.keys(): # For each type of order
    for j in range(J): # For each order
        if i == "veg" or i == "fru": # Because veggies and fruits are in the same passage
            t[i].append(len_shelf/v_df[i][j])
        else: # Because others are in different passege
            t[i].append(len_pass/v_df[i][j])
t_df = pd.DataFrame(t)
t_df['Sum'] = t_df.sum(axis=1) # We will use it later and we will fix it to the real amount of time that will take to do the order
t_df

           veg         fru    oth          Sum
0   214.645362  253.008578  410.0   877.653940
1   349.165254   96.065361  410.0   855.230615
2   131.950791  212.592458  430.0   774.543249
3   214.645362  172.866485  410.0   797.511847
4   303.143313  253.008578  370.0   926.151892
5   258.260303  253.008578  430.0   941.268882
6   493.125549   96.065361  450.0  1039.190909
7   396.223298  133.959533  450.0   980.182831
8   444.233423  377.581073  350.0  1171.814497
9   303.143313  377.581073  390.0  1070.724387
10  303.143313   59.512056  470.0   832.655370
11  303.143313  335.564848  290.0   928.708162
12  303.143313   96.065361  390.0   789.208674
13  303.143313  377.581073  510.0  1190.724387
14  542.840237  172.866485  810.0  1525.706722
15  303.143313  172.866485  410.0   886.009798
16  303.143313  294.022555  330.0   927.165869
17  258.260303  212.592458  390.0   860.852761
18  258.260303   59.512056  450.0   767.772360
19  396.223298  172.866485  390.0   959.089783
20  644.539473  172.866485  450.0  1267.405958
21  396.223298  335.564848  450.0  1181.788146
22  258.260303  212.592458  430.0   900.852761
23  396.223298  253.008578  330.0   979.231876
24  349.165254   96.065361  530.0   975.230615
25  214.645362  253.008578  490.0   957.653940
26  258.260303  133.959533  530.0   922.219836
27  493.125549  172.866485  470.0  1135.992034
28  303.143313  294.022555  330.0   927.165869
29   93.429820  377.581073  470.0   941.010894
30  303.143313  212.592458  570.0  1085.735771
31  131.950791  172.866485  350.0   654.817276
32  542.840237   96.065361  490.0  1128.905598
33  303.143313  172.866485  450.0   926.009798
34  214.645362  253.008578  250.0   717.653940
35  303.143313  133.959533  390.0   827.102846
36  303.143313  172.866485  370.0   846.009798
37  396.223298  294.022555  450.0  1140.245853
38  214.645362  212.592458  470.0   897.237820
39  396.223298  212.592458  470.0  1078.815756
40  349.165254  133.959533  450.0   933.124787
41  396.223298  172.866485  690.0  1259.089783
42  349.165254  172.866485  270.0   792.031739
43  349.165254  294.022555  450.0  1093.187809
44  303.143313  212.592458  490.0  1005.735771
45  396.223298  294.022555  470.0  1160.245853
46  303.143313  377.581073  530.0  1210.724387
47  258.260303  172.866485  470.0   901.126788
48  303.143313  172.866485  610.0  1086.009798
49  258.260303  212.592458  370.0   840.852761

### Question no. 1

For more info, look at the docs:

In [57]:
def internal_arrangement(t_df, len_pass): # This function recives a time matrix, and we will use it for q2
    c = [0 for i in range(J)] # Definig end time matrix
    schedule = [0 for i in range(J)] # Defining the schedule for each order
    # Defining clock of the simulation
    t_now = 0 
    t_prev = 0
    for j in range(J): # For each order
        if m_df[1][j] > 0 or m_df[2][j] > 0: # If there are fruits or veggies to collect
            schedule[j] += t_now # Schedule the order for now
            t_prev = t_now 
            #if m_df[1][j] > 0: # If there are veggies, collect them
            t_now += t_df["veg"][j]
            #if m_df[2][j] > 0: # if ther are fruits, collect them
            t_now += t_df["fru"][j]
            if m_df[3][j] > 0: # If there are others, return back and collect them
                t_now += len_pass + t_df["oth"][j]
            t_df["Sum"][j] = t_now - t_prev # Fixing the sum collumn
            c[j] = t_now # Defining the end time of the order after all the collections
        else: # There are only others to collect
            t_now += t_df["oth"][j]
            c[j] = t_now # Defining the end time of the order after all the collections
    return c, schedule
c,schedule = internal_arrangement(t_df, len_pass)
max(c) # The answer to the question

51375.38279671485

Translating seconds to hours:

In [58]:
max(c)/(60*60)

14.270939665754126

The schedule of the orders:

In [59]:
schedule

[0,
 927.6539404882061,
 1832.8845552448577,
 2657.4278040289837,
 3504.9396513064776,
 4481.091542930975,
 5472.3604245324395,
 6561.551334013303,
 7591.73416471439,
 8813.548661275765,
 9934.27304793362,
 10816.92841767571,
 11795.636579223938,
 12634.845253151714,
 13875.56963980957,
 15451.27636193009,
 16387.286160343876,
 17364.45202893664,
 18275.304789922524,
 19093.07714964158,
 20102.166932868564,
 21419.572890825573,
 22651.361037186998,
 23602.21379817288,
 24631.445674610575,
 25656.676289367228,
 26664.330229855434,
 27636.55006572029,
 28822.542099687165,
 29799.70796827993,
 30790.718862106867,
 31926.454633115784,
 32631.271909304778,
 33810.17750693929,
 34786.18730535307,
 35553.84124584128,
 36430.944091729165,
 37326.95389014295,
 38517.19974354891,
 39464.43756342153,
 40593.253319243646,
 41576.37810596041,
 42885.46788918739,
 43727.49962843006,
 44870.6874378517,
 45926.423208860615,
 47136.66906226658,
 48397.39344892443,
 49348.520237315184,
 50484.53003572897]

The fixed time matrix:

In [60]:
t_df

           veg         fru    oth          Sum
0   214.645362  253.008578  410.0   927.653940
1   349.165254   96.065361  410.0   905.230615
2   131.950791  212.592458  430.0   824.543249
3   214.645362  172.866485  410.0   847.511847
4   303.143313  253.008578  370.0   976.151892
5   258.260303  253.008578  430.0   991.268882
6   493.125549   96.065361  450.0  1089.190909
7   396.223298  133.959533  450.0  1030.182831
8   444.233423  377.581073  350.0  1221.814497
9   303.143313  377.581073  390.0  1120.724387
10  303.143313   59.512056  470.0   882.655370
11  303.143313  335.564848  290.0   978.708162
12  303.143313   96.065361  390.0   839.208674
13  303.143313  377.581073  510.0  1240.724387
14  542.840237  172.866485  810.0  1575.706722
15  303.143313  172.866485  410.0   936.009798
16  303.143313  294.022555  330.0   977.165869
17  258.260303  212.592458  390.0   910.852761
18  258.260303   59.512056  450.0   817.772360
19  396.223298  172.866485  390.0  1009.089783
20  644.539473  172.866485  450.0  1317.405958
21  396.223298  335.564848  450.0  1231.788146
22  258.260303  212.592458  430.0   950.852761
23  396.223298  253.008578  330.0  1029.231876
24  349.165254   96.065361  530.0  1025.230615
25  214.645362  253.008578  490.0  1007.653940
26  258.260303  133.959533  530.0   972.219836
27  493.125549  172.866485  470.0  1185.992034
28  303.143313  294.022555  330.0   977.165869
29   93.429820  377.581073  470.0   991.010894
30  303.143313  212.592458  570.0  1135.735771
31  131.950791  172.866485  350.0   704.817276
32  542.840237   96.065361  490.0  1178.905598
33  303.143313  172.866485  450.0   976.009798
34  214.645362  253.008578  250.0   767.653940
35  303.143313  133.959533  390.0   877.102846
36  303.143313  172.866485  370.0   896.009798
37  396.223298  294.022555  450.0  1190.245853
38  214.645362  212.592458  470.0   947.237820
39  396.223298  212.592458  470.0  1128.815756
40  349.165254  133.959533  450.0   983.124787
41  396.223298  172.866485  690.0  1309.089783
42  349.165254  172.866485  270.0   842.031739
43  349.165254  294.022555  450.0  1143.187809
44  303.143313  212.592458  490.0  1055.735771
45  396.223298  294.022555  470.0  1210.245853
46  303.143313  377.581073  530.0  1260.724387
47  258.260303  172.866485  470.0   951.126788
48  303.143313  172.866485  610.0  1136.009798
49  258.260303  212.592458  370.0   890.852761

### Question no. 2

For more info, look at the docs:

Definig the waiting time of all the orders:

In [61]:
w = [0 for i in range(J)]

Defining the spt algoritem function, we will use it also at question no. 2:

In [62]:
def spt_algo(t_df):
    t_now = 0
    #t_prev = t_now
    t_copy = t_df["Sum"].copy() # Creating a copy of the fixed sum column, because we don't want to lose this info
    schedule = [0 for i in range(J)] # Defining the schedule for each order
    c = [0 for i in range(J)] # Definig end time matrix, only for proving a point
    for i in range(J): # For each order
        #t_prev = t_now
        index = t_copy.idxmin() # Pull the id of the minimal processing time
        schedule[index] += t_now # Scheduling the shortest order for current time
        t_now += t_copy[index] # Moving the sim clock to the end of the order
        c[i] = t_now # Definig the end time of the order
        w[i] = c[i] - t_df["Sum"][index] # Calculating the waiting time: end time - processing time
        print("c[i]: ",c[i])
        print("t_df['Sum'][index]: ", t_df["Sum"][index])
        t_copy[index] = None # "Deleting" the minimal processing time, so we can find the next minimal time
    return schedule, c, w
sche_spt,c_spt, w = spt_algo(t_df)
sche_spt

c[i]:  704.8172761889946
t_df['Sum'][index]:  704.8172761889946
c[i]:  1472.4712166772006
t_df['Sum'][index]:  767.653940488206
c[i]:  2290.2435763962567
t_df['Sum'][index]:  817.7723597190561
c[i]:  3114.786825180383
t_df['Sum'][index]:  824.543248784126
c[i]:  3953.9954991081595
t_df['Sum'][index]:  839.2086739277765
c[i]:  4796.027238350825
t_df['Sum'][index]:  842.0317392426659
c[i]:  5643.539085628319
t_df['Sum'][index]:  847.5118472774939
c[i]:  6520.641931516206
t_df['Sum'][index]:  877.1028458878864
c[i]:  7403.297301258295
t_df['Sum'][index]:  882.6553697420895
c[i]:  8294.150062244182
t_df['Sum'][index]:  890.8527609858866
c[i]:  9190.159860657965
t_df['Sum'][index]:  896.0097984137828
c[i]:  10095.390475414617
t_df['Sum'][index]:  905.2306147566516
c[i]:  11006.2432364005
t_df['Sum'][index]:  910.8527609858829
c[i]:  11933.897176888706
t_df['Sum'][index]:  927.6539404882061
c[i]:  12869.906975302492
t_df['Sum'][index]:  936.0097984137865
c[i]:  13817.144795175114
t_df['Sum'][index]:  947.2378198726219
c[i]:  14767.997556160997
t_df['Sum'][index]:  950.8527609858829
c[i]:  15719.124344551754
t_df['Sum'][index]:  951.1267883907567
c[i]:  16691.34418041661
t_df['Sum'][index]:  972.2198358648566
c[i]:  17667.353978830393
t_df['Sum'][index]:  976.0097984137828
c[i]:  18643.50587045489
t_df['Sum'][index]:  976.1518916244977
c[i]:  19620.671739047655
t_df['Sum'][index]:  977.165868592765
c[i]:  20597.83760764042
t_df['Sum'][index]:  977.165868592765
c[i]:  21576.545769188648
t_df['Sum'][index]:  978.7081615482275
c[i]:  22559.67055590541
t_df['Sum'][index]:  983.1247867167622
c[i]:  23550.681449732347
t_df['Sum'][index]:  991.0108938269368
c[i]:  24541.95033133381
t_df['Sum'][index]:  991.2688816014643
c[i]:  25549.604271822016
t_df['Sum'][index]:  1007.653940488206
c[i]:  26558.694055049
t_df['Sum'][index]:  1009.0897832269839
c[i]:  27583.924669805652
t_df['Sum'][index]:  1025.2306147566524
c[i]:  28613.156546243346
t_df['Sum'][index]:  1029.2318764376942
c[i]:  29643.339376944434
t_df['Sum'][index]:  1030.1828307010874
c[i]:  30699.075147953346
t_df['Sum'][index]:  1055.7357710089127
c[i]:  31788.266057434208
t_df['Sum'][index]:  1089.1909094808634
c[i]:  32908.990444092065
t_df['Sum'][index]:  1120.7243866578556
c[i]:  34037.80619991418
t_df['Sum'][index]:  1128.8157558221137
c[i]:  35173.54197092309
t_df['Sum'][index]:  1135.7357710089163
c[i]:  36309.551769336875
t_df['Sum'][index]:  1136.0097984137828
c[i]:  37452.73957875852
t_df['Sum'][index]:  1143.1878094216445
c[i]:  38631.64517639303
t_df['Sum'][index]:  1178.9055976345117
c[i]:  39817.637210359906
t_df['Sum'][index]:  1185.9920339668752
c[i]:  41007.88306376587
t_df['Sum'][index]:  1190.2458534059624
c[i]:  42218.12891717183
t_df['Sum'][index]:  1210.2458534059624
c[i]:  43439.94341373321
t_df['Sum'][index]:  1221.8144965613747
c[i]:  44671.73156009463
t_df['Sum'][index]:  1231.7881463614249
c[i]:  45912.45594675249
t_df['Sum'][index]:  1240.7243866578556
c[i]:  47173.18033341034
t_df['Sum'][index]:  1260.7243866578501
c[i]:  48482.27011663732
t_df['Sum'][index]:  1309.0897832269839
c[i]:  49799.67607459433
t_df['Sum'][index]:  1317.4059579570094
c[i]:  51375.38279671485
t_df['Sum'][index]:  1575.7067221205198

[11006.2432364005,
 9190.159860657965,
 2290.2435763962567,
 4796.027238350825,
 17667.353978830393,
 23550.681449732347,
 30699.075147953346,
 28613.156546243346,
 42218.12891717183,
 31788.266057434208,
 6520.641931516206,
 20597.83760764042,
 3114.786825180383,
 44671.73156009463,
 49799.67607459433,
 11933.897176888706,
 18643.50587045489,
 10095.390475414617,
 1472.4712166772006,
 25549.604271822016,
 48482.27011663732,
 43439.94341373321,
 13817.144795175114,
 27583.924669805652,
 26558.694055049,
 24541.95033133381,
 15719.124344551754,
 38631.64517639303,
 19620.671739047655,
 22559.67055590541,
 34037.80619991418,
 0,
 37452.73957875852,
 16691.34418041661,
 704.8172761889946,
 5643.539085628319,
 8294.150062244182,
 39817.637210359906,
 12869.906975302492,
 32908.990444092065,
 21576.545769188648,
 47173.18033341034,
 3953.9954991081595,
 36309.551769336875,
 29643.339376944434,
 41007.88306376587,
 45912.45594675249,
 14767.997556160997,
 35173.54197092309,
 7403.297301258295]

Note: We will use sche_spt in question 3.

The waiting time matrix:

In [63]:
w

[0.0,
 704.8172761889946,
 1472.4712166772006,
 2290.2435763962567,
 3114.786825180383,
 3953.9954991081595,
 4796.027238350825,
 5643.539085628319,
 6520.641931516206,
 7403.297301258295,
 8294.150062244182,
 9190.159860657965,
 10095.390475414617,
 11006.2432364005,
 11933.897176888706,
 12869.906975302492,
 13817.144795175114,
 14767.997556160997,
 15719.124344551754,
 16691.34418041661,
 17667.353978830393,
 18643.50587045489,
 19620.671739047655,
 20597.83760764042,
 21576.545769188648,
 22559.67055590541,
 23550.681449732347,
 24541.95033133381,
 25549.604271822016,
 26558.694055049,
 27583.924669805652,
 28613.156546243346,
 29643.339376944434,
 30699.075147953343,
 31788.266057434208,
 32908.990444092065,
 34037.80619991418,
 35173.54197092309,
 36309.551769336875,
 37452.73957875852,
 38631.64517639303,
 39817.637210359906,
 41007.88306376587,
 42218.12891717183,
 43439.94341373321,
 44671.73156009463,
 45912.45594675249,
 47173.18033341034,
 48482.27011663732,
 49799.67607459433]

The proof that c isn't dependent on the scheduling of the order:

In [64]:
max(c_spt)

51375.38279671485

The average waiting time for order:

In [65]:
sum(w)/J

22930.33275633681

### Question no. 3

First, we will calculate v and t for the new collector:

In [66]:
v2_df = v_df.copy()
v2_df = v2_df*1.15
v2_df

         veg       fru       oth
0   0.133942  0.113633  0.140244
1   0.082339  0.299275  0.140244
2   0.217884  0.135235  0.133721
3   0.133942  0.166313  0.140244
4   0.094840  0.113633  0.155405
5   0.111322  0.113633  0.133721
6   0.058302  0.299275  0.127778
7   0.072560  0.214617  0.127778
8   0.064718  0.076143  0.164286
9   0.094840  0.076143  0.147436
10  0.094840  0.483095  0.122340
11  0.094840  0.085676  0.198276
12  0.094840  0.299275  0.147436
13  0.094840  0.076143  0.112745
14  0.052962  0.166313  0.070988
15  0.094840  0.166313  0.140244
16  0.094840  0.097782  0.174242
17  0.111322  0.135235  0.147436
18  0.111322  0.483095  0.127778
19  0.072560  0.166313  0.147436
20  0.044605  0.166313  0.127778
21  0.072560  0.085676  0.127778
22  0.111322  0.135235  0.133721
23  0.072560  0.113633  0.174242
24  0.082339  0.299275  0.108491
25  0.133942  0.113633  0.117347
26  0.111322  0.214617  0.108491
27  0.058302  0.166313  0.122340
28  0.094840  0.097782  0.174242
29  0.307718  0.076143  0.122340
30  0.094840  0.135235  0.100877
31  0.217884  0.166313  0.164286
32  0.052962  0.299275  0.117347
33  0.094840  0.166313  0.127778
34  0.133942  0.113633  0.230000
35  0.094840  0.214617  0.147436
36  0.094840  0.166313  0.155405
37  0.072560  0.097782  0.127778
38  0.133942  0.135235  0.122340
39  0.072560  0.135235  0.122340
40  0.082339  0.214617  0.127778
41  0.072560  0.166313  0.083333
42  0.082339  0.166313  0.212963
43  0.082339  0.097782  0.127778
44  0.094840  0.135235  0.117347
45  0.072560  0.097782  0.122340
46  0.094840  0.076143  0.108491
47  0.111322  0.166313  0.122340
48  0.094840  0.166313  0.094262
49  0.111322  0.135235  0.155405

In [67]:
t2 = {"veg":[],"fru":[], "oth":[]}
for i in t2.keys():
    for j in range(J):
        if i == "veg" or i == "fru":
            t2[i].append(len_shelf/v2_df[i][j])
        else:
            t2[i].append(len_pass/v2_df[i][j])
t2_df = pd.DataFrame(t2)
t2_df['Sum'] = t2_df.sum(axis=1)
t2_df

           veg         fru         oth          Sum
0   186.648141  220.007459  356.521739   763.177340
1   303.621960   83.535096  356.521739   743.678795
2   114.739818  184.863007  373.913043   673.515869
3   186.648141  150.318683  356.521739   693.488563
4   263.602881  220.007459  321.739130   805.349471
5   224.574177  220.007459  373.913043   818.494680
6   428.804825   83.535096  391.304348   903.644269
7   344.541998  116.486550  391.304348   852.332896
8   386.289933  328.331368  304.347826  1018.969127
9   263.602881  328.331368  339.130435   931.064684
10  263.602881   51.749614  408.695652   724.048148
11  263.602881  291.795520  252.173913   807.572314
12  263.602881   83.535096  339.130435   686.268412
13  263.602881  328.331368  443.478261  1035.412510
14  472.034989  150.318683  704.347826  1326.701497
15  263.602881  150.318683  356.521739   770.443303
16  263.602881  255.671787  286.956522   806.231190
17  224.574177  184.863007  339.130435   748.567618
18  224.574177   51.749614  391.304348   667.628139
19  344.541998  150.318683  339.130435   833.991116
20  560.469107  150.318683  391.304348  1102.092137
21  344.541998  291.795520  391.304348  1027.641866
22  224.574177  184.863007  373.913043   783.350227
23  344.541998  220.007459  286.956522   851.505980
24  303.621960   83.535096  460.869565   848.026622
25  186.648141  220.007459  426.086957   832.742557
26  224.574177  116.486550  460.869565   801.930292
27  428.804825  150.318683  408.695652   987.819160
28  263.602881  255.671787  286.956522   806.231190
29   81.243322  328.331368  408.695652   818.270342
30  263.602881  184.863007  495.652174   944.118062
31  114.739818  150.318683  304.347826   569.406327
32  472.034989   83.535096  426.086957   981.657041
33  263.602881  150.318683  391.304348   805.225912
34  186.648141  220.007459  217.391304   624.046905
35  263.602881  116.486550  339.130435   719.219866
36  263.602881  150.318683  321.739130   735.660694
37  344.541998  255.671787  391.304348   991.518133
38  186.648141  184.863007  408.695652   780.206800
39  344.541998  184.863007  408.695652   938.100657
40  303.621960  116.486550  391.304348   811.412858
41  344.541998  150.318683  600.000000  1094.860681
42  303.621960  150.318683  234.782609   688.723252
43  303.621960  255.671787  391.304348   950.598095
44  263.602881  184.863007  426.086957   874.552844
45  344.541998  255.671787  408.695652  1008.909438
46  263.602881  328.331368  460.869565  1052.803814
47  224.574177  150.318683  408.695652   783.588512
48  263.602881  150.318683  530.434783   944.356346
49  224.574177  184.863007  321.739130   731.176314

In [68]:
internal_arrangement(t2_df, len_pass = len_pass/1.15)
spt_algo(t2_df)
t2_df

c[i]:  612.8845879904293
t_df['Sum'][index]:  612.8845879904293
c[i]:  1280.409753632346
t_df['Sum'][index]:  667.5251656419168
c[i]:  1991.5161533880491
t_df['Sum'][index]:  711.106399755703
c[i]:  2708.51028276555
t_df['Sum'][index]:  716.9941293775009
c[i]:  3438.256955746225
t_df['Sum'][index]:  729.7466729806747
c[i]:  4170.458468131144
t_df['Sum'][index]:  732.2015123849196
c[i]:  4907.4252918507045
t_df['Sum'][index]:  736.9668237195601
c[i]:  5670.12341870974
t_df['Sum'][index]:  762.6981268590353
c[i]:  6437.6498271811215
t_df['Sum'][index]:  767.5264084713817
c[i]:  7212.304401951449
t_df['Sum'][index]:  774.6545747703276
c[i]:  7991.443357093871
t_df['Sum'][index]:  779.1389551424218
c[i]:  8778.600413404003
t_df['Sum'][index]:  787.1570563101319
c[i]:  9570.646292522162
t_df['Sum'][index]:  792.0458791181591
c[i]:  10377.301892946689
t_df['Sum'][index]:  806.655600424527
c[i]:  11191.223456784763
t_df['Sum'][index]:  813.9215638380738
c[i]:  12014.908517543568
t_df['Sum'][index]:  823.6850607588058
c[i]:  12841.737005357383
t_df['Sum'][index]:  826.8284878138147
c[i]:  13668.803777871079
t_df['Sum'][index]:  827.0667725136955
c[i]:  14514.21233079704
t_df['Sum'][index]:  845.408552925961
c[i]:  15362.916503330765
t_df['Sum'][index]:  848.7041725337258
c[i]:  16211.744235178154
t_df['Sum'][index]:  848.8277318473893
c[i]:  17061.453686128385
t_df['Sum'][index]:  849.7094509502313
c[i]:  17911.163137078616
t_df['Sum'][index]:  849.7094509502313
c[i]:  18762.213712337943
t_df['Sum'][index]:  851.050575259329
c[i]:  19617.10483122209
t_df['Sum'][index]:  854.8911188841448
c[i]:  20478.853434549863
t_df['Sum'][index]:  861.7486033277746
c[i]:  21340.826375072877
t_df['Sum'][index]:  861.9729405230128
c[i]:  22217.047192888705
t_df['Sum'][index]:  876.2208178158289
c[i]:  23094.51656960782
t_df['Sum'][index]:  877.4693767191129
c[i]:  23986.02145200491
t_df['Sum'][index]:  891.5048823970901
c[i]:  24881.00569238551
t_df['Sum'][index]:  894.9842403806033
c[i]:  25776.816849516894
t_df['Sum'][index]:  895.8111571313802
c[i]:  26694.847954742043
t_df['Sum'][index]:  918.0311052251491
c[i]:  27641.970484725403
t_df['Sum'][index]:  947.1225299833586
c[i]:  28616.513429645278
t_df['Sum'][index]:  974.5429449198746
c[i]:  29598.09234775147
t_df['Sum'][index]:  981.5789181061918
c[i]:  30585.68867036792
t_df['Sum'][index]:  987.5963226164495
c[i]:  31573.52327768426
t_df['Sum'][index]:  987.8346073163411
c[i]:  32567.59963370308
t_df['Sum'][index]:  994.0763560188207
c[i]:  33592.734935993954
t_df['Sum'][index]:  1025.135302290877
c[i]:  34624.032356834716
t_df['Sum'][index]:  1031.2974208407613
c[i]:  35659.02875110078
t_df['Sum'][index]:  1034.9963942660615
c[i]:  36711.41644971466
t_df['Sum'][index]:  1052.3876986138857
c[i]:  37773.863838028905
t_df['Sum'][index]:  1062.4473883142382
c[i]:  38844.9839652997
t_df['Sum'][index]:  1071.1201272708022
c[i]:  39923.874736306534
t_df['Sum'][index]:  1078.8907710068306
c[i]:  41020.156811661196
t_df['Sum'][index]:  1096.282075354662
c[i]:  42158.49575359771
t_df['Sum'][index]:  1138.3389419365121
c[i]:  43304.0661518212
t_df['Sum'][index]:  1145.5703982234882
c[i]:  44674.245910186866
t_df['Sum'][index]:  1370.179758365668

           veg         fru         oth          Sum
0   186.648141  220.007459  356.521739   806.655600
1   303.621960   83.535096  356.521739   787.157056
2   114.739818  184.863007  373.913043   716.994129
3   186.648141  150.318683  356.521739   736.966824
4   263.602881  220.007459  321.739130   848.827732
5   224.574177  220.007459  373.913043   861.972941
6   428.804825   83.535096  391.304348   947.122530
7   344.541998  116.486550  391.304348   895.811157
8   386.289933  328.331368  304.347826  1062.447388
9   263.602881  328.331368  339.130435   974.542945
10  263.602881   51.749614  408.695652   767.526408
11  263.602881  291.795520  252.173913   851.050575
12  263.602881   83.535096  339.130435   729.746673
13  263.602881  328.331368  443.478261  1078.890771
14  472.034989  150.318683  704.347826  1370.179758
15  263.602881  150.318683  356.521739   813.921564
16  263.602881  255.671787  286.956522   849.709451
17  224.574177  184.863007  339.130435   792.045879
18  224.574177   51.749614  391.304348   711.106400
19  344.541998  150.318683  339.130435   877.469377
20  560.469107  150.318683  391.304348  1145.570398
21  344.541998  291.795520  391.304348  1071.120127
22  224.574177  184.863007  373.913043   826.828488
23  344.541998  220.007459  286.956522   894.984240
24  303.621960   83.535096  460.869565   891.504882
25  186.648141  220.007459  426.086957   876.220818
26  224.574177  116.486550  460.869565   845.408553
27  428.804825  150.318683  408.695652  1031.297421
28  263.602881  255.671787  286.956522   849.709451
29   81.243322  328.331368  408.695652   861.748603
30  263.602881  184.863007  495.652174   987.596323
31  114.739818  150.318683  304.347826   612.884588
32  472.034989   83.535096  426.086957  1025.135302
33  263.602881  150.318683  391.304348   848.704173
34  186.648141  220.007459  217.391304   667.525166
35  263.602881  116.486550  339.130435   762.698127
36  263.602881  150.318683  321.739130   779.138955
37  344.541998  255.671787  391.304348  1034.996394
38  186.648141  184.863007  408.695652   823.685061
39  344.541998  184.863007  408.695652   981.578918
40  303.621960  116.486550  391.304348   854.891119
41  344.541998  150.318683  600.000000  1138.338942
42  303.621960  150.318683  234.782609   732.201512
43  303.621960  255.671787  391.304348   994.076356
44  263.602881  184.863007  426.086957   918.031105
45  344.541998  255.671787  408.695652  1052.387699
46  263.602881  328.331368  460.869565  1096.282075
47  224.574177  150.318683  408.695652   827.066773
48  263.602881  150.318683  530.434783   987.834607
49  224.574177  184.863007  321.739130   774.654575

prep for Q//c_max - for more info go to doc:

calc the ratio of the task index (K) to the working rate of the gatherer (s_j: s1 = 1, s2 = 1.15): K/s_j

In [69]:
K_S1 = [i for i in range(1, J+1)]

K_S2 = [0 for i in range(1, J+1)]
for i in range(1, 51):
    K_S2[i-1] = i/1.15

As we do in Q//sigma(C_i): take the task with the longest time and match it to the min ratio of both gatherers.

* The heuristics will be to place the tasks from the beginning and not the end (as we do in P//c_max). 

* Note the longest task will be the same for the both gatherers since the ratio is permanent

In [70]:
#initializing schedules: 1 for the regular, 2 for the faster one
sch_1_Q3 = []
sch_2_Q3 = []

#initializing time counters
time_1 = 0
time_2 = 0

# to compare with Q4 - initializing dictionaries for waiting time to each task in specific gather. 
waiting_time_1 = {}
waiting_time_2 = {}

#copy for processing times
t_df_copy = t_df.copy()


for i in range(J):
    task_idx = t_df_copy['Sum'].idxmax() # task index with max time
    task_time_1 = t_df_copy['Sum'][task_idx] # time processing for the regular
    task_time_2 = t2_df['Sum'][task_idx] ## time processing for the fast gather

    t_df_copy['Sum'][task_idx] = None # for not using it again
    
    # taking min ratio
    min_K_S1 = min(K_S1)
    min_K_S2 = min(K_S2)
    
    min_tot = 0
    
    #case the min ratio is for the regular gather
    if min_K_S1 < min_K_S2:
        waiting_time_1[task_idx] = time_1 # waiting time until now, not including the process time for this task
        min_tot = min_K_S1
        idx = K_S1.index(min_tot)
        K_S1.pop(idx)
            
        sch_1_Q3.append(task_idx) # add the task to regular gather schedule
            
        time_1 += task_time_1 # update time
    
    #case the min ratio is for the fast gather    
    else:
        waiting_time_2[task_idx] = time_2 # waiting time until now, not including the process time for this task
        min_tot = min_K_S2
        idx = K_S2.index(min_tot)
        K_S2.pop(idx)
            
        sch_2_Q3.append(task_idx) # add the task to faster gather schedule
            
        time_2 += task_time_2 # update time


time_finish = max(time_2, time_1) # C_MAX

print('time_finish: ',time_finish)
print('sch for regular gather: ', sch_1_Q3)
print('sch for fast gather: ', sch_2_Q3)

time_finish:  24192.884244894303
sch for regular gather:  [20, 46, 21, 45, 27, 43, 39, 6, 7, 24, 25, 29, 11, 4, 26, 22, 15, 17, 36, 35, 42, 2, 34]
sch for fast gather:  [14, 41, 13, 8, 37, 32, 48, 30, 9, 44, 23, 19, 5, 40, 16, 28, 33, 47, 38, 0, 1, 49, 10, 3, 12, 18, 31]

In [71]:
#to compare woth Q4
total_wt_1 = sum(list(waiting_time_1.values()))
avg_wt_1 = total_wt_1/len(list(waiting_time_1.values()))

total_wt_2 = sum(list(waiting_time_2.values()))
avg_wt_2 = total_wt_2/len(list(waiting_time_2.values()))

total_wt_both = total_wt_1 + total_wt_2
avg_wt__both = total_wt_both/J

### Question no. 4

re-calc the ratio of the task index (K) to the working rate of the gatherer (s_j: s1 = 1, s2 = 1.15): K/s_j

In [72]:
#prep for the ratios 
K_S1_Q4 = [i for i in range(1, J+1)]

K_S2_Q4 = [0 for i in range(1, J+1)]
for i in range(1, 51):
    K_S2_Q4[i-1] = i/1.15

As we do in Q//sigma(C_i): take the task with the longest time and match it to the min ratio of both gatherers. 

* Will place the tasks from end to beginning as should do in Q//sigma(C_i). 

* Note the longest task will be the same for the both gatherers since the ratio is permanent

In [73]:
#initializing schedules: 1 for the regular, 2 for the faster one
sch_1_Q4 = []
sch_2_Q4 = []

#initializing time counters
time_1_Q4 = 0
time_2_Q4 = 0

# initializing dictionaries for waiting time to each task in specific gather. 
waiting_time_1_Q4 = {}
waiting_time_2_Q4 = {}

#copy for processing times
t_Q4_copy = t_df.copy()

### same algo as Q3 - no time clculations
for i in range(J):
    task_idx = t_Q4_copy['Sum'].idxmax() # task index with max time
    task_time_1 = t_Q4_copy['Sum'][task_idx] # time processing for the regular
    task_time_2 = t2_df['Sum'][task_idx] ## time processing for the fast gather
    
    t_Q4_copy['Sum'][task_idx] = None # for not using it again
    
    # taking min ratio
    min_K_S1 = min(K_S1_Q4)
    min_K_S2 = min(K_S2_Q4)
    
    min_tot = 0
    
    #case the min ratio is for the regular gather
    if min_K_S1 < min_K_S2:
        min_tot = min_K_S1
        idx = K_S1_Q4.index(min_tot)
        K_S1_Q4.pop(idx)
            
        sch_1_Q4.append([task_idx, task_time_1]) # add the task to regular gather schedule
    
    #case the min ratio is for the fast gather    
    else:
        min_tot = min_K_S2
        idx = K_S2_Q4.index(min_tot)
        K_S2_Q4.pop(idx)
            
        sch_2_Q4.append([task_idx,task_time_2]) # add the task to faster gather schedule
###

### New - Assign tasks from end to beginning
t1=0 # time (regular gather) counter
agg_time_1 = [0] # Auxiliary variable in order to calculate waiting time 
sch_1_rev = [] # Auxiliary variable to reverse scheduale
sch_1_final = []

for i in range(len(sch_1_Q4)):
    sch_1_rev.append(sch_1_Q4[-1])
    t1 += sch_1_Q4[-1][1]  # accumulation
    sch_1_Q4.pop(-1)
    
    agg_time_1.append(t1) # list of waiting time - no task index
    
    waiting_time_1_Q4[sch_1_rev[i][0]] = agg_time_1[i] # dict of waiting time- k= task, v= waiting time (reg gather)
    
    sch_1_final.append(sch_1_rev[i][0])


t2=0 # time (fast gather) counter
agg_time_2 = [0] # Auxiliary variable in order to calculate waiting time
sch_2_rev = [] # Auxiliary variable to reverse scheduale
sch_2_final = []

for i in range(len(sch_2_Q4)):
    sch_2_rev.append(sch_2_Q4[-1]) 
    t2 += sch_2_Q4[-1][1] # accumulation
    sch_2_Q4.pop(-1)
    
    agg_time_2.append(t2) # list of waiting time - no task index
    
    waiting_time_2_Q4[sch_2_rev[i][0]] = agg_time_2[i] # dict of waiting time- k= task, v= waiting time (fast gather)
    
    sch_2_final.append(sch_2_rev[i][0])


time_finish_Q4 = max(agg_time_1[-1], agg_time_2[-1]) # C_MAX

print('time_finish Q4: ', time_finish_Q4)
print('sch for regular gather: ', sch_1_final)
print('sch for fast gather: ', sch_2_final)

time_finish Q4:  24192.884244894303
sch for regular gather:  [34, 2, 42, 35, 36, 17, 15, 22, 26, 4, 11, 29, 25, 24, 7, 6, 39, 43, 27, 45, 21, 46, 20]
sch for fast gather:  [31, 18, 12, 3, 10, 49, 1, 0, 38, 47, 33, 28, 16, 40, 5, 19, 23, 44, 9, 30, 48, 32, 37, 8, 13, 41, 14]

As we expected all schedules are reversed (Q3 vs Q4). 

Now will compare waiting time:

In [74]:
#print('waiting_time for 1: ', waiting_time_1_Q4.items())
total_wt_1_Q4 = sum(list(waiting_time_1_Q4.values()))
avg_wt_1_Q4 = total_wt_1_Q4/len(list(waiting_time_1_Q4.values()))
print('Regular worker:')
print('-----------------------------------------------------')
print('The total waiting time in Q3: ',total_wt_1, 'and the avg waiting time: ',avg_wt_1)
print('Total waiting time Q4: ',total_wt_1_Q4, ' and avg waiting time Q4: ', avg_wt_1_Q4)

print('-----------------------------------------------------')
print('-----------------------------------------------------')


total_wt_2_Q4 = sum(list(waiting_time_2_Q4.values()))
avg_wt_2_Q4 = total_wt_2_Q4/len(list(waiting_time_2_Q4.values()))
print('Fast worker:')
print('-----------------------------------------------------')
print('The total waiting time in Q3: ',total_wt_2, 'and the avg waiting time in Q3: ',avg_wt_2)
print('Total waiting time Q4: ', total_wt_2_Q4,'and avg waiting tine Q4: ',avg_wt_2_Q4)

print('-----------------------------------------------------')
print('-----------------------------------------------------')

total_wt_both_Q4 = total_wt_1_Q4 + total_wt_2_Q4
avg_wt__both_Q4 = total_wt_both_Q4/J
print('Both workers:')
print('-----------------------------------------------------')
print('The total waiting time in Q3: ',total_wt_both,' and The avg waiting time in Q3: ',avg_wt__both)
print('Total waiting time Q4: ', total_wt_both_Q4, ' and avg waiting time Q4: ',avg_wt__both_Q4)

Regular worker:
-----------------------------------------------------
The total waiting time in Q3:  280913.520891279 and the avg waiting time:  12213.631343099087
Total waiting time Q4:  237264.92924062247  and avg waiting time Q4:  10315.866488722717
-----------------------------------------------------
-----------------------------------------------------
Fast worker:
-----------------------------------------------------
The total waiting time in Q3:  344800.746807722 and the avg waiting time in Q3:  12770.39802991563
Total waiting time Q4:  284214.2435595298 and avg waiting tine Q4:  10526.45346516777
-----------------------------------------------------
-----------------------------------------------------
Both workers:
-----------------------------------------------------
The total waiting time in Q3:  625714.267699001  and The avg waiting time in Q3:  12514.28535398002
Total waiting time Q4:  521479.1728001522  and avg waiting time Q4:  10429.583456003043

### Question no. 5

Redefinig the time metrix that takes to do each type of order for each worker, by using velpcity matrix:

In [75]:
t5 = {"veg":[],"fru":[], "oth":[]} # A dataframe of collector's times
for i in t5.keys(): # For each type of order
    for j in range(J): # For each order
        if i == "veg" or i == "fru": # Because veggies and fruits are in the same passage
            t5[i].append(len_shelf/v2_df[i][j]) # only for worker 2 - the fast worker
        else: # Because others are in different passege
            t5[i].append(len_pass/v_df[i][j]) # only for worker 1 - the regular worker
t5_df = pd.DataFrame(t)
t5_df['Sum'] = t5_df["veg"] + t5_df["fru"] # only for worker 2 - the fast worker 
t5_df

           veg         fru    oth         Sum
0   214.645362  253.008578  410.0  467.653940
1   349.165254   96.065361  410.0  445.230615
2   131.950791  212.592458  430.0  344.543249
3   214.645362  172.866485  410.0  387.511847
4   303.143313  253.008578  370.0  556.151892
5   258.260303  253.008578  430.0  511.268882
6   493.125549   96.065361  450.0  589.190909
7   396.223298  133.959533  450.0  530.182831
8   444.233423  377.581073  350.0  821.814497
9   303.143313  377.581073  390.0  680.724387
10  303.143313   59.512056  470.0  362.655370
11  303.143313  335.564848  290.0  638.708162
12  303.143313   96.065361  390.0  399.208674
13  303.143313  377.581073  510.0  680.724387
14  542.840237  172.866485  810.0  715.706722
15  303.143313  172.866485  410.0  476.009798
16  303.143313  294.022555  330.0  597.165869
17  258.260303  212.592458  390.0  470.852761
18  258.260303   59.512056  450.0  317.772360
19  396.223298  172.866485  390.0  569.089783
20  644.539473  172.866485  450.0  817.405958
21  396.223298  335.564848  450.0  731.788146
22  258.260303  212.592458  430.0  470.852761
23  396.223298  253.008578  330.0  649.231876
24  349.165254   96.065361  530.0  445.230615
25  214.645362  253.008578  490.0  467.653940
26  258.260303  133.959533  530.0  392.219836
27  493.125549  172.866485  470.0  665.992034
28  303.143313  294.022555  330.0  597.165869
29   93.429820  377.581073  470.0  471.010894
30  303.143313  212.592458  570.0  515.735771
31  131.950791  172.866485  350.0  304.817276
32  542.840237   96.065361  490.0  638.905598
33  303.143313  172.866485  450.0  476.009798
34  214.645362  253.008578  250.0  467.653940
35  303.143313  133.959533  390.0  437.102846
36  303.143313  172.866485  370.0  476.009798
37  396.223298  294.022555  450.0  690.245853
38  214.645362  212.592458  470.0  427.237820
39  396.223298  212.592458  470.0  608.815756
40  349.165254  133.959533  450.0  483.124787
41  396.223298  172.866485  690.0  569.089783
42  349.165254  172.866485  270.0  522.031739
43  349.165254  294.022555  450.0  643.187809
44  303.143313  212.592458  490.0  515.735771
45  396.223298  294.022555  470.0  690.245853
46  303.143313  377.581073  530.0  680.724387
47  258.260303  172.866485  470.0  431.126788
48  303.143313  172.866485  610.0  476.009798
49  258.260303  212.592458  370.0  470.852761

Depends on the assumptions and the work division between the workers -  C_max cannot be minimized. We make sure that each worker handles an order only if necessary, and calculate the finish time accordingly.

In [76]:
#initializing schedules: 1 for the regular, 2 for the faster one
sch_1_Q5 = []
sch_2_Q5 = []

#initializing time counters
time_1_Q5 = 0
time_2_Q5 = 0

# to compare with Q6 - initializing dictionaries for waiting time to each task in specific gather. 
waiting_time_1_Q5 = {}
waiting_time_2_Q5 = {}

#copy for processing times
t5_df_copy = t5_df.copy()

def internal_arrangement_Q5(t_df): # This function recives a time matrix, and we will use it for q2
    c1 = [0 for i in range(J)] # Definig end time matrix - for worker 1
    c2 = [0 for i in range(J)] # Definig end time matrix - for worker 2
    schedule1 = [0 for i in range(J)] # Defining the schedule for each order - for worker 1
    schedule2 = [0 for i in range(J)] # Defining the schedule for each order - for worker 2
    # Defining clock of the simulation
    t1_now = 0
    t2_now = 0 
    t1_prev = 0
    t2_prev = 0
    for j in range(J): # For each order 
        if m_df[1][j] > 0 or m_df[2][j] > 0: # If there are fruits or veggies to collect - for worker 2
            schedule1[j] += t1_now # Schedule the order for now
            t1_prev = t1_now 
            t1_now += t5_df["veg"][j]
            t1_now += t5_df["fru"][j]
            c1[j] = t1_now # Defining the end time of the order after all the collections
        if m_df[3][j] > 0: # if there are others to collect - for worker 1
            schedule2[j] += t2_now # Schedule the order for now
            t2_prev = t2_now 
            t2_now += t5_df["oth"][j]
            c2[j] = t2_now # Defining the end time of the order after all the collections

    return c1, c2, schedule1, schedule2

c1, c2, schedule1, schedule2 = internal_arrangement_Q5(t5_df)
c1_max = max(c1)
c2_max = max(c2)
time_finish_Q5 = max(c1_max, c2_max) # C_MAX

In [77]:
time_finish_Q5/(60*60)

7.44316188797635

In [78]:
schedule1

[0,
 467.6539404882061,
 912.8845552448578,
 1257.427804028984,
 1644.9396513064778,
 2201.0915429309753,
 2712.3604245324395,
 3301.551334013303,
 3831.73416471439,
 4653.548661275764,
 5334.273047933619,
 5696.928417675707,
 6335.636579223934,
 6734.84525315171,
 7415.569639809564,
 8131.276361930083,
 8607.286160343869,
 9204.452028936634,
 9675.304789922517,
 9993.077149641573,
 10562.166932868557,
 11379.572890825568,
 12111.361037186995,
 12582.213798172877,
 13231.445674610573,
 13676.676289367226,
 14144.330229855432,
 14536.550065720287,
 15202.54209968716,
 15799.707968279925,
 16270.718862106864,
 16786.45463311578,
 17091.271909304774,
 17730.177506939282,
 18206.18730535307,
 18673.841245841275,
 19110.944091729165,
 19586.95389014295,
 20277.199743548914,
 20704.43756342154,
 21313.253319243653,
 21796.37810596042,
 22365.467889187403,
 22887.499628430065,
 23530.687437851706,
 24046.423208860622,
 24736.669062266585,
 25417.39344892444,
 25848.52023731519,
 26324.530035728978]

In [79]:
schedule2

[0,
 410.0,
 820.0,
 1250.0,
 1660.0,
 2030.0,
 2460.0,
 2910.0,
 3360.0,
 3710.0,
 4100.0,
 4570.0,
 4860.0,
 5250.0,
 5760.0,
 6570.0,
 6980.0,
 7310.0,
 7700.0,
 8150.0,
 8540.0,
 8990.0,
 9440.0,
 9870.0,
 10200.0,
 10730.0,
 11220.0,
 11750.0,
 12220.0,
 12550.0,
 13020.0,
 13590.0,
 13940.0,
 14430.0,
 14880.0,
 15130.0,
 15520.0,
 15890.0,
 16340.0,
 16810.0,
 17280.0,
 17730.0,
 18420.0,
 18690.0,
 19140.0,
 19630.0,
 20100.0,
 20630.0,
 21100.0,
 21710.0]

### Question no. 6

In [86]:
only_worker1 = {} # "oth"
only_worker2 = {} # "veg" & "fru"

for i in range(J): # For each order:
    if m_df[1][j] == 0 and m_df[2][j] == 0 and m_df[3][j] > 0:
        only_worker1[i] = t5_df["oth"][i]
    if (m_df[1][j] > 0 or m_df[2][j] > 0) and m_df[3][j] == 0:
        only_worker1[i] = t5_df["Sum"][i]
dict(sorted(only_worker1.items(), key=lambda item: item[1]))
dict(sorted(only_worker2.items(), key=lambda item: item[1]))

sch_1_Q6 = {i : None for i in range(50)}
sch_2_Q6 = {i : None for i in range(50)}

def get_key(dic, val):
    for key, value in dic.items():
         if val == value:
             return key

def spt_algo_Q6(t_df):
    
    t1_now = 0
    t2_now = 0 
    t_oth_copy = t5_df["oth"].copy() # Creating a copy of  'Sum' column - for worker 1
    t_sum_copy = t5_df["Sum"].copy() # Creating a copy of 'oth' column - for worker 2
    c1 = [0 for i in range(J)] # Definig end time matrix - for worker 1
    c2 = [0 for i in range(J)] # Definig end time matrix - for worker 2
    schedule1 = [0 for i in range(J)] # Defining the schedule for each order - for worker 1
    schedule2 = [0 for i in range(J)] # Defining the schedule for each order - for worker 2
    w1 = [0 for i in range(J)]
    w2 = [0 for i in range(J)]

    for i in range(J): # For each order
        index = t_oth_copy.idxmin() # Pull the id of the minimal processing time
        schedule1[index] += t1_now # Scheduling the shortest order for current time
        t1_now += t_oth_copy[index] # Moving the sim clock to the end of the order
        c1[i] = t1_now # Definig the end time of the order
        w1[i] = c1[i] - t_oth_copy[index] # Calculating the waiting time: end time - processing time
        # print("c1[i]: ",c1[i])
        # print("t_oth_copy[index]: ", t_oth_copy[index])
        t_oth_copy[index] = None # "Deleting" the minimal processing time, so we can find the next minimal time
        sch_1_Q6[i]= index

        if not i in only_worker1:
            sch_2_Q6[i] = index

    for i in range (len(only_worker2)): # For each exclusive order of worker 2
        if only_worker1: # If there is an exclusive task of worker 1
            cur_val = list(only_worker1.values())[0] # Worker1's shortest order
            key_to_pop = get_key(only_worker1, cur_val) 
            only_worker1.pop(key_to_pop) # Pop the current order, because we referred to it
            rel_key = get_key(sch_1_Q6, cur_val) # Get the serial number of the current order by the schedule of worker 1
        else:
            rel_key = get_key(sch_2_Q6, None) # Get a serial number of "free time slot" of worker 2
        sch_2_Q6[rel_key] = only_worker1[i] # Insert the exclusive order of worker 2

    for key, val in sch_2_Q6:
        schedule2[val] += t2_now # Scheduling the shortest order for current time
        t2_now += t_sum_copy[val] # Moving the sim clock to the end of the order
        c2[key] = t2_now # Definig the end time of the order
        w2[key] = c2[key] - t_oth_copy[val] # Calculating the waiting time: end time - processing time
    
    return sch_1_Q6, schedule1, c1, w1, sch_2_Q6, schedule2, c2, w2
    
sche_1_lst, sche_1_spt, c1_spt, w1_spt, sche_2_lst, sche_2_spt, c2_spt, w2_spt = spt_algo_Q6(t5_df)
sche_1_lst

[34,
 42,
 11,
 16,
 23,
 28,
 8,
 31,
 4,
 36,
 49,
 9,
 12,
 17,
 19,
 35,
 0,
 1,
 3,
 15,
 2,
 5,
 22,
 6,
 7,
 18,
 20,
 21,
 33,
 37,
 40,
 43,
 10,
 27,
 29,
 38,
 39,
 45,
 47,
 25,
 32,
 44,
 13,
 24,
 26,
 46,
 30,
 48,
 41,
 14]